// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comparison_session.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDocumentToComparisonSession = `-- name: AddDocumentToComparisonSession :one
INSERT INTO comparison_session_documents (session_id, document_id, organization_id, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (session_id, document_id) DO UPDATE
    SET position = EXCLUDED.position
RETURNING session_id, document_id, organization_id, position
`

type AddDocumentToComparisonSessionParams struct {
	SessionID      uuid.UUID `json:"session_id"`
	DocumentID     uuid.UUID `json:"document_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Position       int16     `json:"position"`
}

func (q *Queries) AddDocumentToComparisonSession(ctx context.Context, arg AddDocumentToComparisonSessionParams) (ComparisonSessionDocument, error) {
	row := q.db.QueryRow(ctx, addDocumentToComparisonSession,
		arg.SessionID,
		arg.DocumentID,
		arg.OrganizationID,
		arg.Position,
	)
	var i ComparisonSessionDocument
	err := row.Scan(
		&i.SessionID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Position,
	)
	return i, err
}

const createComparisonSession = `-- name: CreateComparisonSession :one
INSERT INTO comparison_sessions (organization_id, created_by, name, contract_kind_id)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, created_by, name, contract_kind_id, created_at
`

type CreateComparisonSessionParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
	Name           pgtype.Text `json:"name"`
	ContractKindID pgtype.UUID `json:"contract_kind_id"`
}

func (q *Queries) CreateComparisonSession(ctx context.Context, arg CreateComparisonSessionParams) (ComparisonSession, error) {
	row := q.db.QueryRow(ctx, createComparisonSession,
		arg.OrganizationID,
		arg.CreatedBy,
		arg.Name,
		arg.ContractKindID,
	)
	var i ComparisonSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.ContractKindID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComparisonSession = `-- name: DeleteComparisonSession :execrows
DELETE FROM comparison_sessions
WHERE id = $1 AND organization_id = $2
`

type DeleteComparisonSessionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteComparisonSession(ctx context.Context, arg DeleteComparisonSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComparisonSession, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComparisonSession = `-- name: GetComparisonSession :one
SELECT id, organization_id, created_by, name, contract_kind_id, created_at FROM comparison_sessions
WHERE id = $1 AND organization_id = $2
`

type GetComparisonSessionParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetComparisonSession(ctx context.Context, arg GetComparisonSessionParams) (ComparisonSession, error) {
	row := q.db.QueryRow(ctx, getComparisonSession, arg.ID, arg.OrganizationID)
	var i ComparisonSession
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedBy,
		&i.Name,
		&i.ContractKindID,
		&i.CreatedAt,
	)
	return i, err
}

const listComparisonSessionDocuments = `-- name: ListComparisonSessionDocuments :many
SELECT session_id, document_id, organization_id, position FROM comparison_session_documents
WHERE session_id = $1
ORDER BY position ASC
`

func (q *Queries) ListComparisonSessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]ComparisonSessionDocument, error) {
	rows, err := q.db.Query(ctx, listComparisonSessionDocuments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComparisonSessionDocument{}
	for rows.Next() {
		var i ComparisonSessionDocument
		if err := rows.Scan(
			&i.SessionID,
			&i.DocumentID,
			&i.OrganizationID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparisonSessionsByOrg = `-- name: ListComparisonSessionsByOrg :many
SELECT id, organization_id, created_by, name, contract_kind_id, created_at FROM comparison_sessions
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListComparisonSessionsByOrg(ctx context.Context, organizationID uuid.UUID) ([]ComparisonSession, error) {
	rows, err := q.db.Query(ctx, listComparisonSessionsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComparisonSession{}
	for rows.Next() {
		var i ComparisonSession
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedBy,
			&i.Name,
			&i.ContractKindID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentFromComparisonSession = `-- name: RemoveDocumentFromComparisonSession :execrows
DELETE FROM comparison_session_documents
WHERE session_id = $1 AND document_id = $2
`

type RemoveDocumentFromComparisonSessionParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	DocumentID uuid.UUID `json:"document_id"`
}

func (q *Queries) RemoveDocumentFromComparisonSession(ctx context.Context, arg RemoveDocumentFromComparisonSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeDocumentFromComparisonSession, arg.SessionID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
