// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: construction_site.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConstructionSite = `-- name: CreateConstructionSite :one
INSERT INTO construction_sites (organization_id, parent_id, name, status, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at
`

type CreateConstructionSiteParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Name           string      `json:"name"`
	Status         string      `json:"status"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateConstructionSite(ctx context.Context, arg CreateConstructionSiteParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, createConstructionSite,
		arg.OrganizationID,
		arg.ParentID,
		arg.Name,
		arg.Status,
		arg.CreatedBy,
	)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverImagePath,
		&i.CoverImageUploadedAt,
		&i.SiteType,
		&i.LastActivityAt,
	)
	return i, err
}

const deleteConstructionSite = `-- name: DeleteConstructionSite :execrows
DELETE FROM construction_sites WHERE id = $1 AND organization_id = $2
`

type DeleteConstructionSiteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteConstructionSite(ctx context.Context, arg DeleteConstructionSiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConstructionSite, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConstructionSite = `-- name: GetConstructionSite :one
SELECT id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at FROM construction_sites
WHERE id = $1 AND organization_id = $2
`

type GetConstructionSiteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetConstructionSite(ctx context.Context, arg GetConstructionSiteParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, getConstructionSite, arg.ID, arg.OrganizationID)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverImagePath,
		&i.CoverImageUploadedAt,
		&i.SiteType,
		&i.LastActivityAt,
	)
	return i, err
}

const getSiteAncestors = `-- name: GetSiteAncestors :many
WITH RECURSIVE ancestry AS (
    SELECT cs.id, cs.name, cs.parent_id, 0 AS depth
    FROM construction_sites cs
    WHERE cs.id = $1 AND cs.organization_id = $2
    UNION ALL
    SELECT p.id, p.name, p.parent_id, a.depth + 1
    FROM construction_sites p
    JOIN ancestry a ON p.id = a.parent_id
)
SELECT name FROM ancestry ORDER BY depth DESC
`

type GetSiteAncestorsParams struct {
	SiteID         uuid.UUID `json:"site_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Returns ancestors of a site ordered from root to the site itself.
func (q *Queries) GetSiteAncestors(ctx context.Context, arg GetSiteAncestorsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getSiteAncestors, arg.SiteID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConstructionSitesByOrganization = `-- name: ListConstructionSitesByOrganization :many
SELECT id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at FROM construction_sites
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConstructionSitesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ConstructionSite, error) {
	rows, err := q.db.Query(ctx, listConstructionSitesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConstructionSite{}
	for rows.Next() {
		var i ConstructionSite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoverImagePath,
			&i.CoverImageUploadedAt,
			&i.SiteType,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConstructionSitesByParent = `-- name: ListConstructionSitesByParent :many
SELECT id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at FROM construction_sites
WHERE organization_id = $1 AND parent_id = $2
ORDER BY last_activity_at DESC
`

type ListConstructionSitesByParentParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListConstructionSitesByParent(ctx context.Context, arg ListConstructionSitesByParentParams) ([]ConstructionSite, error) {
	rows, err := q.db.Query(ctx, listConstructionSitesByParent, arg.OrganizationID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConstructionSite{}
	for rows.Next() {
		var i ConstructionSite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoverImagePath,
			&i.CoverImageUploadedAt,
			&i.SiteType,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootConstructionSites = `-- name: ListRootConstructionSites :many
SELECT id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at FROM construction_sites
WHERE organization_id = $1 AND parent_id IS NULL
ORDER BY last_activity_at DESC
`

func (q *Queries) ListRootConstructionSites(ctx context.Context, organizationID uuid.UUID) ([]ConstructionSite, error) {
	rows, err := q.db.Query(ctx, listRootConstructionSites, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConstructionSite{}
	for rows.Next() {
		var i ConstructionSite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoverImagePath,
			&i.CoverImageUploadedAt,
			&i.SiteType,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteContractKinds = `-- name: ListSiteContractKinds :many
SELECT d.site_id, ck.id, ck.display_name, ck.is_active
FROM documents d
JOIN document_contract_kinds ck ON ck.id = d.contract_kind_id
WHERE d.organization_id = $1
  AND d.site_id = ANY($2::uuid[])
  AND d.parent_id IS NULL
  AND d.contract_kind_id IS NOT NULL
GROUP BY d.site_id, ck.id, ck.display_name, ck.is_active
`

type ListSiteContractKindsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteIds        []uuid.UUID `json:"site_ids"`
}

type ListSiteContractKindsRow struct {
	SiteID      pgtype.UUID `json:"site_id"`
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	IsActive    bool        `json:"is_active"`
}

// Returns distinct contract kinds for documents in each of the given sites.
func (q *Queries) ListSiteContractKinds(ctx context.Context, arg ListSiteContractKindsParams) ([]ListSiteContractKindsRow, error) {
	rows, err := q.db.Query(ctx, listSiteContractKinds, arg.OrganizationID, arg.SiteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteContractKindsRow{}
	for rows.Next() {
		var i ListSiteContractKindsRow
		if err := rows.Scan(
			&i.SiteID,
			&i.ID,
			&i.DisplayName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteExtractedCounts = `-- name: ListSiteExtractedCounts :many
SELECT d.site_id, COUNT(ded.id)::bigint AS extracted_count
FROM documents d
JOIN document_extracted_data ded
    ON ded.document_id = d.id AND ded.organization_id = d.organization_id
WHERE d.organization_id = $1
  AND d.site_id = ANY($2::uuid[])
  AND d.parent_id IS NULL
GROUP BY d.site_id
`

type ListSiteExtractedCountsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteIds        []uuid.UUID `json:"site_ids"`
}

type ListSiteExtractedCountsRow struct {
	SiteID         pgtype.UUID `json:"site_id"`
	ExtractedCount int64       `json:"extracted_count"`
}

// Returns extracted parameter count per site for a given list of site IDs.
func (q *Queries) ListSiteExtractedCounts(ctx context.Context, arg ListSiteExtractedCountsParams) ([]ListSiteExtractedCountsRow, error) {
	rows, err := q.db.Query(ctx, listSiteExtractedCounts, arg.OrganizationID, arg.SiteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteExtractedCountsRow{}
	for rows.Next() {
		var i ListSiteExtractedCountsRow
		if err := rows.Scan(&i.SiteID, &i.ExtractedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConstructionSite = `-- name: UpdateConstructionSite :one
UPDATE construction_sites
SET name       = $3,
    status     = $4,
    updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at
`

type UpdateConstructionSiteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateConstructionSite(ctx context.Context, arg UpdateConstructionSiteParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, updateConstructionSite,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Status,
	)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverImagePath,
		&i.CoverImageUploadedAt,
		&i.SiteType,
		&i.LastActivityAt,
	)
	return i, err
}

const updateConstructionSiteCover = `-- name: UpdateConstructionSiteCover :one
UPDATE construction_sites
SET cover_image_path        = $3,
    cover_image_uploaded_at = CASE WHEN $3 IS NOT NULL THEN now() ELSE cover_image_uploaded_at END,
    updated_at              = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at
`

type UpdateConstructionSiteCoverParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	CoverImagePath pgtype.Text `json:"cover_image_path"`
}

func (q *Queries) UpdateConstructionSiteCover(ctx context.Context, arg UpdateConstructionSiteCoverParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, updateConstructionSiteCover, arg.ID, arg.OrganizationID, arg.CoverImagePath)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverImagePath,
		&i.CoverImageUploadedAt,
		&i.SiteType,
		&i.LastActivityAt,
	)
	return i, err
}

const updateConstructionSiteType = `-- name: UpdateConstructionSiteType :one
UPDATE construction_sites
SET site_type  = $3,
    updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, parent_id, name, status, created_by, created_at, updated_at, cover_image_path, cover_image_uploaded_at, site_type, last_activity_at
`

type UpdateConstructionSiteTypeParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteType       pgtype.Text `json:"site_type"`
}

func (q *Queries) UpdateConstructionSiteType(ctx context.Context, arg UpdateConstructionSiteTypeParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, updateConstructionSiteType, arg.ID, arg.OrganizationID, arg.SiteType)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverImagePath,
		&i.CoverImageUploadedAt,
		&i.SiteType,
		&i.LastActivityAt,
	)
	return i, err
}
