// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: construction_site.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConstructionSite = `-- name: CreateConstructionSite :one
INSERT INTO construction_sites (organization_id, parent_id, name, status, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, parent_id, name, status, created_by, created_at, updated_at
`

type CreateConstructionSiteParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Name           string      `json:"name"`
	Status         string      `json:"status"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateConstructionSite(ctx context.Context, arg CreateConstructionSiteParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, createConstructionSite,
		arg.OrganizationID,
		arg.ParentID,
		arg.Name,
		arg.Status,
		arg.CreatedBy,
	)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConstructionSite = `-- name: DeleteConstructionSite :execrows
DELETE FROM construction_sites WHERE id = $1 AND organization_id = $2
`

type DeleteConstructionSiteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteConstructionSite(ctx context.Context, arg DeleteConstructionSiteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConstructionSite, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConstructionSite = `-- name: GetConstructionSite :one
SELECT id, organization_id, parent_id, name, status, created_by, created_at, updated_at FROM construction_sites
WHERE id = $1 AND organization_id = $2
`

type GetConstructionSiteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetConstructionSite(ctx context.Context, arg GetConstructionSiteParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, getConstructionSite, arg.ID, arg.OrganizationID)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConstructionSitesByOrganization = `-- name: ListConstructionSitesByOrganization :many
SELECT id, organization_id, parent_id, name, status, created_by, created_at, updated_at FROM construction_sites
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConstructionSitesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ConstructionSite, error) {
	rows, err := q.db.Query(ctx, listConstructionSitesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConstructionSite{}
	for rows.Next() {
		var i ConstructionSite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ParentID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConstructionSite = `-- name: UpdateConstructionSite :one
UPDATE construction_sites
SET name       = $3,
    status     = $4,
    updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, parent_id, name, status, created_by, created_at, updated_at
`

type UpdateConstructionSiteParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateConstructionSite(ctx context.Context, arg UpdateConstructionSiteParams) (ConstructionSite, error) {
	row := q.db.QueryRow(ctx, updateConstructionSite,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Status,
	)
	var i ConstructionSite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ParentID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
