// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract_kind.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContractKind = `-- name: CreateContractKind :one
INSERT INTO document_contract_kinds (organization_id, display_name, sort_order, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, display_name, sort_order, is_active, created_at, updated_at
`

type CreateContractKindParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	DisplayName    string      `json:"display_name"`
	SortOrder      int16       `json:"sort_order"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) CreateContractKind(ctx context.Context, arg CreateContractKindParams) (DocumentContractKind, error) {
	row := q.db.QueryRow(ctx, createContractKind,
		arg.OrganizationID,
		arg.DisplayName,
		arg.SortOrder,
		arg.IsActive,
	)
	var i DocumentContractKind
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContractKind = `-- name: DeleteContractKind :execrows
DELETE FROM document_contract_kinds
WHERE id = $1 AND organization_id = $2
`

type DeleteContractKindParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteContractKind(ctx context.Context, arg DeleteContractKindParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContractKind, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContractKind = `-- name: GetContractKind :one
SELECT id, organization_id, display_name, sort_order, is_active, created_at, updated_at FROM document_contract_kinds
WHERE id = $1
  AND (organization_id = $2::uuid OR organization_id IS NULL)
`

type GetContractKindParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) GetContractKind(ctx context.Context, arg GetContractKindParams) (DocumentContractKind, error) {
	row := q.db.QueryRow(ctx, getContractKind, arg.ID, arg.Column2)
	var i DocumentContractKind
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContractKindsByOrg = `-- name: ListContractKindsByOrg :many
SELECT id, organization_id, display_name, sort_order, is_active, created_at, updated_at FROM document_contract_kinds
WHERE organization_id = $1::uuid OR organization_id IS NULL
ORDER BY sort_order ASC, display_name ASC
`

// Returns all contract kinds visible to the given tenant: org-specific AND system kinds (organization_id IS NULL).
func (q *Queries) ListContractKindsByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]DocumentContractKind, error) {
	rows, err := q.db.Query(ctx, listContractKindsByOrg, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentContractKind{}
	for rows.Next() {
		var i DocumentContractKind
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DisplayName,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContractKind = `-- name: UpdateContractKind :one
UPDATE document_contract_kinds
SET display_name = $3,
    sort_order   = $4,
    is_active    = $5,
    updated_at   = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, display_name, sort_order, is_active, created_at, updated_at
`

type UpdateContractKindParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	DisplayName    string      `json:"display_name"`
	SortOrder      int16       `json:"sort_order"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateContractKind(ctx context.Context, arg UpdateContractKindParams) (DocumentContractKind, error) {
	row := q.db.QueryRow(ctx, updateContractKind,
		arg.ID,
		arg.OrganizationID,
		arg.DisplayName,
		arg.SortOrder,
		arg.IsActive,
	)
	var i DocumentContractKind
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
