// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at
`

type CreateDocumentParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteID         pgtype.UUID `json:"site_id"`
	UploadedBy     uuid.UUID   `json:"uploaded_by"`
	ParentID       pgtype.UUID `json:"parent_id"`
	FileName       string      `json:"file_name"`
	StoragePath    string      `json:"storage_path"`
	MimeType       pgtype.Text `json:"mime_type"`
	FileSizeBytes  pgtype.Int8 `json:"file_size_bytes"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OrganizationID,
		arg.SiteID,
		arg.UploadedBy,
		arg.ParentID,
		arg.FileName,
		arg.StoragePath,
		arg.MimeType,
		arg.FileSizeBytes,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentTask = `-- name: CreateDocumentTask :one

INSERT INTO document_tasks (document_id, module_name)
VALUES ($1, $2)
RETURNING id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at
`

type CreateDocumentTaskParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	ModuleName string    `json:"module_name"`
}

// ── Document Tasks ──────────────────────────────────
func (q *Queries) CreateDocumentTask(ctx context.Context, arg CreateDocumentTaskParams) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, createDocumentTask, arg.DocumentID, arg.ModuleName)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const deleteDocumentTask = `-- name: DeleteDocumentTask :exec
DELETE FROM document_tasks WHERE id = $1
`

func (q *Queries) DeleteDocumentTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentTask, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentTask = `-- name: GetDocumentTask :one
SELECT id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at FROM document_tasks WHERE id = $1
`

func (q *Queries) GetDocumentTask(ctx context.Context, id uuid.UUID) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, getDocumentTask, id)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByOrganization = `-- name: ListDocumentsByOrganization :many
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at FROM documents
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.UploadedBy,
			&i.ParentID,
			&i.FileName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsBySite = `-- name: ListDocumentsBySite :many
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at FROM documents
WHERE site_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsBySite(ctx context.Context, siteID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.UploadedBy,
			&i.ParentID,
			&i.FileName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByDocument = `-- name: ListTasksByDocument :many
SELECT id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at FROM document_tasks
WHERE document_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByDocument(ctx context.Context, documentID uuid.UUID) ([]DocumentTask, error) {
	rows, err := q.db.Query(ctx, listTasksByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentTask{}
	for rows.Next() {
		var i DocumentTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ModuleName,
			&i.Status,
			&i.CeleryTaskID,
			&i.ResultPayload,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentTaskStatus = `-- name: UpdateDocumentTaskStatus :one
UPDATE document_tasks SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at
`

type UpdateDocumentTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDocumentTaskStatus(ctx context.Context, arg UpdateDocumentTaskStatusParams) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, updateDocumentTaskStatus, arg.ID, arg.Status)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
