// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifactDocument = `-- name: CreateArtifactDocument :one
INSERT INTO documents (organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (parent_id, artifact_kind) WHERE parent_id IS NOT NULL
DO UPDATE SET
    file_name       = EXCLUDED.file_name,
    storage_path    = EXCLUDED.storage_path,
    mime_type       = EXCLUDED.mime_type,
    file_size_bytes = EXCLUDED.file_size_bytes,
    updated_at      = now()
RETURNING id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id
`

type CreateArtifactDocumentParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteID         pgtype.UUID `json:"site_id"`
	UploadedBy     uuid.UUID   `json:"uploaded_by"`
	ParentID       pgtype.UUID `json:"parent_id"`
	FileName       string      `json:"file_name"`
	StoragePath    string      `json:"storage_path"`
	MimeType       pgtype.Text `json:"mime_type"`
	FileSizeBytes  pgtype.Int8 `json:"file_size_bytes"`
	ArtifactKind   pgtype.Text `json:"artifact_kind"`
}

// Idempotent artifact creation: on conflict (parent_id, artifact_kind) updates
// artifact metadata from the latest callback so that RETURNING yields the current row state.
// Prevents duplicate artifact documents when a worker sends a duplicate 'completed' callback.
func (q *Queries) CreateArtifactDocument(ctx context.Context, arg CreateArtifactDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createArtifactDocument,
		arg.OrganizationID,
		arg.SiteID,
		arg.UploadedBy,
		arg.ParentID,
		arg.FileName,
		arg.StoragePath,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.ArtifactKind,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.ArtifactKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractKindID,
		&i.FileRoleID,
		&i.BundleID,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id
`

type CreateDocumentParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteID         pgtype.UUID `json:"site_id"`
	UploadedBy     uuid.UUID   `json:"uploaded_by"`
	ParentID       pgtype.UUID `json:"parent_id"`
	FileName       string      `json:"file_name"`
	StoragePath    string      `json:"storage_path"`
	MimeType       pgtype.Text `json:"mime_type"`
	FileSizeBytes  pgtype.Int8 `json:"file_size_bytes"`
	ArtifactKind   pgtype.Text `json:"artifact_kind"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OrganizationID,
		arg.SiteID,
		arg.UploadedBy,
		arg.ParentID,
		arg.FileName,
		arg.StoragePath,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.ArtifactKind,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.ArtifactKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractKindID,
		&i.FileRoleID,
		&i.BundleID,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id = $1 AND organization_id = $2
`

type DeleteDocumentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id FROM documents
WHERE id = $1 AND organization_id = $2
`

type GetDocumentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.OrganizationID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.ArtifactKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractKindID,
		&i.FileRoleID,
		&i.BundleID,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id FROM documents WHERE id = $1
`

// WARNING: This lookup is intentionally unscoped by organization_id.
// Callers MUST enforce organization isolation at the service layer.
// Prefer GetDocument when organization-scoped access is required.
func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.ArtifactKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractKindID,
		&i.FileRoleID,
		&i.BundleID,
	)
	return i, err
}

const listDocumentsByParent = `-- name: ListDocumentsByParent :many
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id FROM documents
WHERE parent_id = $1 AND organization_id = $2
ORDER BY created_at ASC
`

type ListDocumentsByParentParams struct {
	ParentID       pgtype.UUID `json:"parent_id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
}

// Все артефакты, порождённые данным документом; scoped by organization_id for tenant isolation.
func (q *Queries) ListDocumentsByParent(ctx context.Context, arg ListDocumentsByParentParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByParent, arg.ParentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.UploadedBy,
			&i.ParentID,
			&i.FileName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.ArtifactKind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContractKindID,
			&i.FileRoleID,
			&i.BundleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDocumentsByOrganization = `-- name: ListRootDocumentsByOrganization :many
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id FROM documents
WHERE organization_id = $1 AND parent_id IS NULL
ORDER BY created_at DESC
`

// Только корневые документы (загруженные пользователем, не артефакты)
func (q *Queries) ListRootDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listRootDocumentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.UploadedBy,
			&i.ParentID,
			&i.FileName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.ArtifactKind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContractKindID,
			&i.FileRoleID,
			&i.BundleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDocumentsBySite = `-- name: ListRootDocumentsBySite :many
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id FROM documents
WHERE organization_id = $1 AND site_id = $2 AND parent_id IS NULL
ORDER BY created_at DESC
`

type ListRootDocumentsBySiteParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteID         pgtype.UUID `json:"site_id"`
}

func (q *Queries) ListRootDocumentsBySite(ctx context.Context, arg ListRootDocumentsBySiteParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listRootDocumentsBySite, arg.OrganizationID, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.UploadedBy,
			&i.ParentID,
			&i.FileName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.ArtifactKind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContractKindID,
			&i.FileRoleID,
			&i.BundleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentMeta = `-- name: UpdateDocumentMeta :one
UPDATE documents
SET contract_kind_id = $3,
    file_role_id     = $4,
    bundle_id        = $5,
    updated_at       = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, artifact_kind, created_at, updated_at, contract_kind_id, file_role_id, bundle_id
`

type UpdateDocumentMetaParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	ContractKindID pgtype.UUID `json:"contract_kind_id"`
	FileRoleID     pgtype.UUID `json:"file_role_id"`
	BundleID       pgtype.UUID `json:"bundle_id"`
}

// Updates document classification fields (contract_kind, file_role, bundle).
// Only applicable to root documents (parent_id IS NULL); artifacts are excluded by DB constraint.
func (q *Queries) UpdateDocumentMeta(ctx context.Context, arg UpdateDocumentMetaParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentMeta,
		arg.ID,
		arg.OrganizationID,
		arg.ContractKindID,
		arg.FileRoleID,
		arg.BundleID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.ArtifactKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractKindID,
		&i.FileRoleID,
		&i.BundleID,
	)
	return i, err
}
