// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_task.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentTask = `-- name: CreateDocumentTask :one
INSERT INTO document_tasks (document_id, module_name)
SELECT $1, $2
FROM documents
WHERE documents.id = $1 AND documents.organization_id = $3
RETURNING id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at, retry_count
`

type CreateDocumentTaskParams struct {
	DocumentID     uuid.UUID `json:"document_id"`
	ModuleName     string    `json:"module_name"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) CreateDocumentTask(ctx context.Context, arg CreateDocumentTaskParams) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, createDocumentTask, arg.DocumentID, arg.ModuleName, arg.OrganizationID)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
	)
	return i, err
}

const createDocumentTaskInternal = `-- name: CreateDocumentTaskInternal :one
INSERT INTO document_tasks (document_id, module_name)
VALUES ($1, $2)
ON CONFLICT (document_id, module_name) DO NOTHING
RETURNING id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at, retry_count
`

type CreateDocumentTaskInternalParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	ModuleName string    `json:"module_name"`
}

// Internal: creates a task directly by document_id without tenant org-check.
// Use only from trusted internal paths (worker service); never expose publicly.
// ON CONFLICT DO NOTHING makes this idempotent: duplicate (document_id, module_name)
// returns pgx.ErrNoRows, which callers should treat as "task already exists".
func (q *Queries) CreateDocumentTaskInternal(ctx context.Context, arg CreateDocumentTaskInternalParams) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, createDocumentTaskInternal, arg.DocumentID, arg.ModuleName)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
	)
	return i, err
}

const deleteDocumentTask = `-- name: DeleteDocumentTask :execrows
DELETE FROM document_tasks
WHERE document_tasks.id = $1
  AND document_tasks.document_id IN (SELECT documents.id FROM documents WHERE documents.organization_id = $2)
`

type DeleteDocumentTaskParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteDocumentTask(ctx context.Context, arg DeleteDocumentTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocumentTask, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocumentTask = `-- name: GetDocumentTask :one
SELECT dt.id, dt.document_id, dt.module_name, dt.status, dt.celery_task_id, dt.result_payload, dt.error_message, dt.created_at, dt.updated_at, dt.retry_count
FROM document_tasks AS dt
JOIN documents AS d ON d.id = dt.document_id
WHERE dt.id = $1 AND d.organization_id = $2
`

type GetDocumentTaskParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetDocumentTask(ctx context.Context, arg GetDocumentTaskParams) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, getDocumentTask, arg.ID, arg.OrganizationID)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
	)
	return i, err
}

const listStaleTasks = `-- name: ListStaleTasks :many
SELECT dt.id,
       dt.document_id,
       dt.module_name,
       dt.retry_count,
       d.storage_path
FROM document_tasks dt
JOIN documents d ON d.id = dt.document_id
WHERE dt.status IN ('pending', 'processing')
  AND dt.updated_at < $1
ORDER BY dt.updated_at ASC
`

type ListStaleTasksRow struct {
	ID          uuid.UUID `json:"id"`
	DocumentID  uuid.UUID `json:"document_id"`
	ModuleName  string    `json:"module_name"`
	RetryCount  int32     `json:"retry_count"`
	StoragePath string    `json:"storage_path"`
}

// Watchdog: returns stuck tasks (pending or processing) whose updated_at is older than $1
// (cutoff timestamp), joined with their document's storage_path for re-queuing.
// Covers two failure modes: worker died mid-processing (processing) and
// Redis message was lost before worker picked it up (pending).
// No org-check; caller must be trusted (watchdog goroutine only).
func (q *Queries) ListStaleTasks(ctx context.Context, updatedAt time.Time) ([]ListStaleTasksRow, error) {
	rows, err := q.db.Query(ctx, listStaleTasks, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleTasksRow{}
	for rows.Next() {
		var i ListStaleTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ModuleName,
			&i.RetryCount,
			&i.StoragePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByDocument = `-- name: ListTasksByDocument :many
SELECT dt.id, dt.document_id, dt.module_name, dt.status, dt.celery_task_id, dt.result_payload, dt.error_message, dt.created_at, dt.updated_at, dt.retry_count
FROM document_tasks AS dt
JOIN documents AS d ON d.id = dt.document_id
WHERE dt.document_id = $1 AND d.organization_id = $2
ORDER BY dt.created_at DESC
`

type ListTasksByDocumentParams struct {
	DocumentID     uuid.UUID `json:"document_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListTasksByDocument(ctx context.Context, arg ListTasksByDocumentParams) ([]DocumentTask, error) {
	rows, err := q.db.Query(ctx, listTasksByDocument, arg.DocumentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentTask{}
	for rows.Next() {
		var i DocumentTask
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ModuleName,
			&i.Status,
			&i.CeleryTaskID,
			&i.ResultPayload,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleTaskFailed = `-- name: MarkStaleTaskFailed :execrows
UPDATE document_tasks
SET status        = 'failed',
    error_message = 'stale task: exceeded max retry attempts',
    updated_at    = now()
WHERE id     = $1
  AND status IN ('pending', 'processing')
`

// Watchdog: permanently fails a task that has exhausted all retry attempts.
func (q *Queries) MarkStaleTaskFailed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleTaskFailed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStaleTaskPending = `-- name: MarkStaleTaskPending :execrows
UPDATE document_tasks
SET status      = 'pending',
    retry_count = retry_count + 1,
    updated_at  = now()
WHERE id     = $1
  AND status IN ('pending', 'processing')
`

// Watchdog: atomically resets a stale task to pending and increments retry_count.
// The WHERE status IN (...) guard makes this a compare-and-swap, so two
// concurrent watchdog instances cannot double-claim the same task.
func (q *Queries) MarkStaleTaskPending(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleTaskPending, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentTaskStatus = `-- name: UpdateDocumentTaskStatus :one
UPDATE document_tasks
SET status = $3, updated_at = now()
WHERE document_tasks.id = $1
  AND document_tasks.document_id IN (
    SELECT documents.id FROM documents WHERE documents.organization_id = $2
  )
RETURNING id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at, retry_count
`

type UpdateDocumentTaskStatusParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateDocumentTaskStatus(ctx context.Context, arg UpdateDocumentTaskStatusParams) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, updateDocumentTaskStatus, arg.ID, arg.OrganizationID, arg.Status)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
	)
	return i, err
}

const updateWorkerTaskStatus = `-- name: UpdateWorkerTaskStatus :one
UPDATE document_tasks
SET
    status         = $2,
    celery_task_id = COALESCE($3, celery_task_id),
    result_payload = COALESCE($4, result_payload),
    error_message  = COALESCE($5, error_message),
    updated_at     = now()
WHERE id = $1
RETURNING id, document_id, module_name, status, celery_task_id, result_payload, error_message, created_at, updated_at, retry_count
`

type UpdateWorkerTaskStatusParams struct {
	ID            uuid.UUID       `json:"id"`
	Status        string          `json:"status"`
	CeleryTaskID  pgtype.Text     `json:"celery_task_id"`
	ResultPayload json.RawMessage `json:"result_payload"`
	ErrorMessage  pgtype.Text     `json:"error_message"`
}

// Internal: no org-check; callers must be authenticated via SERVICE_TOKEN.
func (q *Queries) UpdateWorkerTaskStatus(ctx context.Context, arg UpdateWorkerTaskStatusParams) (DocumentTask, error) {
	row := q.db.QueryRow(ctx, updateWorkerTaskStatus,
		arg.ID,
		arg.Status,
		arg.CeleryTaskID,
		arg.ResultPayload,
		arg.ErrorMessage,
	)
	var i DocumentTask
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ModuleName,
		&i.Status,
		&i.CeleryTaskID,
		&i.ResultPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryCount,
	)
	return i, err
}
