// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at
`

type CreateDocumentParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteID         pgtype.UUID `json:"site_id"`
	UploadedBy     uuid.UUID   `json:"uploaded_by"`
	ParentID       pgtype.UUID `json:"parent_id"`
	FileName       string      `json:"file_name"`
	StoragePath    string      `json:"storage_path"`
	MimeType       pgtype.Text `json:"mime_type"`
	FileSizeBytes  pgtype.Int8 `json:"file_size_bytes"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OrganizationID,
		arg.SiteID,
		arg.UploadedBy,
		arg.ParentID,
		arg.FileName,
		arg.StoragePath,
		arg.MimeType,
		arg.FileSizeBytes,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :execrows
DELETE FROM documents WHERE id = $1 AND organization_id = $2
`

type DeleteDocumentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at FROM documents
WHERE id = $1 AND organization_id = $2
`

type GetDocumentParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.OrganizationID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.UploadedBy,
		&i.ParentID,
		&i.FileName,
		&i.StoragePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByOrganization = `-- name: ListDocumentsByOrganization :many
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at FROM documents
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.UploadedBy,
			&i.ParentID,
			&i.FileName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsBySite = `-- name: ListDocumentsBySite :many
SELECT id, organization_id, site_id, uploaded_by, parent_id, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at FROM documents
WHERE organization_id = $1 AND site_id = $2
ORDER BY created_at DESC
`

type ListDocumentsBySiteParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SiteID         pgtype.UUID `json:"site_id"`
}

func (q *Queries) ListDocumentsBySite(ctx context.Context, arg ListDocumentsBySiteParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsBySite, arg.OrganizationID, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.UploadedBy,
			&i.ParentID,
			&i.FileName,
			&i.StoragePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
