// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extraction.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpsertExtractedData = `-- name: BatchUpsertExtractedData :exec
INSERT INTO document_extracted_data (organization_id, document_id, key_id, extracted_value)
SELECT $1::uuid,
       $2::uuid,
       unnest($3::uuid[]),
       unnest($4::text[])
ON CONFLICT ON CONSTRAINT uq_extracted_data_doc_key DO UPDATE
    SET extracted_value = EXCLUDED.extracted_value
`

type BatchUpsertExtractedDataParams struct {
	OrganizationID  uuid.UUID   `json:"organization_id"`
	DocumentID      uuid.UUID   `json:"document_id"`
	KeyIds          []uuid.UUID `json:"key_ids"`
	ExtractedValues []string    `json:"extracted_values"`
}

// Batch idempotent upsert: inserts all extracted key-value pairs for a document
// in a single statement. Two unnest() calls in the SELECT list are expanded
// in lockstep by PostgreSQL (guaranteed since PG 10), zipping key_ids with
// extracted_values row-by-row. FROM unnest(arr, arr) would be cleaner but
// sqlc does not support multi-arg unnest in the FROM clause. On conflict,
// latest value wins.
func (q *Queries) BatchUpsertExtractedData(ctx context.Context, arg BatchUpsertExtractedDataParams) error {
	_, err := q.db.Exec(ctx, batchUpsertExtractedData,
		arg.OrganizationID,
		arg.DocumentID,
		arg.KeyIds,
		arg.ExtractedValues,
	)
	return err
}

const createExtractionKey = `-- name: CreateExtractionKey :one
INSERT INTO extraction_keys (organization_id, key_name, source_query, data_type, display_name)
VALUES ($1::uuid, $2, $3, $4, $5)
RETURNING id, organization_id, key_name, source_query, data_type, created_at, display_name, is_active, category
`

type CreateExtractionKeyParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	KeyName        string      `json:"key_name"`
	SourceQuery    string      `json:"source_query"`
	DataType       string      `json:"data_type"`
	DisplayName    pgtype.Text `json:"display_name"`
}

// Creates an org-specific extraction key. Fails on duplicate (org, key_name).
func (q *Queries) CreateExtractionKey(ctx context.Context, arg CreateExtractionKeyParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, createExtractionKey,
		arg.OrganizationID,
		arg.KeyName,
		arg.SourceQuery,
		arg.DataType,
		arg.DisplayName,
	)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.DataType,
		&i.CreatedAt,
		&i.DisplayName,
		&i.IsActive,
		&i.Category,
	)
	return i, err
}

const deleteExtractionKey = `-- name: DeleteExtractionKey :execrows
DELETE FROM extraction_keys
WHERE id              = $1
  AND organization_id = $2::uuid
`

type DeleteExtractionKeyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Deletes an org-specific extraction key. System keys (org IS NULL) cannot be deleted via this query.
func (q *Queries) DeleteExtractionKey(ctx context.Context, arg DeleteExtractionKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExtractionKey, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExtractionKey = `-- name: GetExtractionKey :one
SELECT id, organization_id, key_name, source_query, data_type, created_at, display_name, is_active, category FROM extraction_keys
WHERE id = $1
  AND (organization_id = $2::uuid OR organization_id IS NULL)
`

type GetExtractionKeyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Tenant-scoped lookup; returns org-specific or system key by id.
// Callers should map pgx.ErrNoRows to 404.
func (q *Queries) GetExtractionKey(ctx context.Context, arg GetExtractionKeyParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, getExtractionKey, arg.ID, arg.OrganizationID)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.DataType,
		&i.CreatedAt,
		&i.DisplayName,
		&i.IsActive,
		&i.Category,
	)
	return i, err
}

const getExtractionKeysByNames = `-- name: GetExtractionKeysByNames :many
SELECT DISTINCT ON (key_name) id, organization_id, key_name, source_query, data_type, created_at, display_name, is_active, category FROM extraction_keys
WHERE key_name = ANY($1::text[])
  AND (organization_id = $2::uuid OR organization_id IS NULL)
ORDER BY key_name, (organization_id IS NULL) ASC
`

type GetExtractionKeysByNamesParams struct {
	KeyNames       []string  `json:"key_names"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Lookup extraction keys by key_name for a tenant. Returns org-specific keys
// and system keys (organization_id IS NULL) that match the given names.
// When both a tenant key and a system key share the same key_name, the tenant
// key is selected (DISTINCT ON + ORDER BY ensures deterministic precedence).
// Used in the extract callback to map key_name → key_id for bulk data insert.
func (q *Queries) GetExtractionKeysByNames(ctx context.Context, arg GetExtractionKeysByNamesParams) ([]ExtractionKey, error) {
	rows, err := q.db.Query(ctx, getExtractionKeysByNames, arg.KeyNames, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtractionKey{}
	for rows.Next() {
		var i ExtractionKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.KeyName,
			&i.SourceQuery,
			&i.DataType,
			&i.CreatedAt,
			&i.DisplayName,
			&i.IsActive,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtractedDataByDocument = `-- name: ListExtractedDataByDocument :many
SELECT ded.id,
       ded.document_id,
       ded.extracted_value,
       k.id              AS key_id,
       k.organization_id AS key_organization_id,
       k.key_name,
       k.source_query,
       k.data_type,
       k.display_name,
       k.created_at      AS key_created_at
FROM document_extracted_data ded
JOIN extraction_keys k ON k.id = ded.key_id
WHERE ded.document_id     = $1::uuid
  AND ded.organization_id = $2::uuid
ORDER BY k.key_name
`

type ListExtractedDataByDocumentParams struct {
	DocumentID     uuid.UUID `json:"document_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

type ListExtractedDataByDocumentRow struct {
	ID                uuid.UUID   `json:"id"`
	DocumentID        uuid.UUID   `json:"document_id"`
	ExtractedValue    pgtype.Text `json:"extracted_value"`
	KeyID             uuid.UUID   `json:"key_id"`
	KeyOrganizationID pgtype.UUID `json:"key_organization_id"`
	KeyName           string      `json:"key_name"`
	SourceQuery       string      `json:"source_query"`
	DataType          string      `json:"data_type"`
	DisplayName       pgtype.Text `json:"display_name"`
	KeyCreatedAt      time.Time   `json:"key_created_at"`
}

// Returns all extracted data for a document joined with key metadata.
// Tenant-scoped: only data belonging to the given org is returned.
// Used by GET /documents/:id/answers.
func (q *Queries) ListExtractedDataByDocument(ctx context.Context, arg ListExtractedDataByDocumentParams) ([]ListExtractedDataByDocumentRow, error) {
	rows, err := q.db.Query(ctx, listExtractedDataByDocument, arg.DocumentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExtractedDataByDocumentRow{}
	for rows.Next() {
		var i ListExtractedDataByDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ExtractedValue,
			&i.KeyID,
			&i.KeyOrganizationID,
			&i.KeyName,
			&i.SourceQuery,
			&i.DataType,
			&i.DisplayName,
			&i.KeyCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtractedDataForKeys = `-- name: ListExtractedDataForKeys :many
SELECT k.key_name,
       k.data_type,
       d.extracted_value
FROM document_extracted_data d
JOIN extraction_keys k ON k.id = d.key_id
WHERE d.document_id     = $1::uuid
  AND d.organization_id = $2::uuid
  AND k.key_name        = ANY($3::text[])
ORDER BY k.key_name
`

type ListExtractedDataForKeysParams struct {
	DocumentID     uuid.UUID `json:"document_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	KeyNames       []string  `json:"key_names"`
}

type ListExtractedDataForKeysRow struct {
	KeyName        string      `json:"key_name"`
	DataType       string      `json:"data_type"`
	ExtractedValue pgtype.Text `json:"extracted_value"`
}

// Returns extracted values for a document filtered to the given extraction
// keys, joined with key metadata. Tenant-scoped: only data and keys visible
// to the given organization (org-specific keys + system keys) are returned.
// Used by GET /extraction-requests/:id to assemble the answers map for a
// specific request's resolved_schema.
func (q *Queries) ListExtractedDataForKeys(ctx context.Context, arg ListExtractedDataForKeysParams) ([]ListExtractedDataForKeysRow, error) {
	rows, err := q.db.Query(ctx, listExtractedDataForKeys, arg.DocumentID, arg.OrganizationID, arg.KeyNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExtractedDataForKeysRow{}
	for rows.Next() {
		var i ListExtractedDataForKeysRow
		if err := rows.Scan(&i.KeyName, &i.DataType, &i.ExtractedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtractionKeysByOrg = `-- name: ListExtractionKeysByOrg :many
SELECT id, organization_id, key_name, source_query, data_type, created_at, display_name, is_active, category FROM extraction_keys
WHERE organization_id = $1::uuid OR organization_id IS NULL
ORDER BY organization_id NULLS LAST, key_name
`

// Returns all keys visible to the given tenant: org-specific keys AND system
// keys (organization_id IS NULL) shared across all tenants.
func (q *Queries) ListExtractionKeysByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]ExtractionKey, error) {
	rows, err := q.db.Query(ctx, listExtractionKeysByOrg, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtractionKey{}
	for rows.Next() {
		var i ExtractionKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.KeyName,
			&i.SourceQuery,
			&i.DataType,
			&i.CreatedAt,
			&i.DisplayName,
			&i.IsActive,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExtractionKey = `-- name: UpdateExtractionKey :one
UPDATE extraction_keys
SET source_query = COALESCE($1, source_query),
    data_type    = COALESCE($2, data_type),
    display_name = COALESCE($3, display_name)
WHERE id              = $4
  AND organization_id = $5::uuid
RETURNING id, organization_id, key_name, source_query, data_type, created_at, display_name, is_active, category
`

type UpdateExtractionKeyParams struct {
	SourceQuery    pgtype.Text `json:"source_query"`
	DataType       pgtype.Text `json:"data_type"`
	DisplayName    pgtype.Text `json:"display_name"`
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
}

// Partial update for org-specific extraction keys; system keys (org IS NULL) are read-only.
// Uses COALESCE for patch semantics: NULL arguments preserve the existing value.
func (q *Queries) UpdateExtractionKey(ctx context.Context, arg UpdateExtractionKeyParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, updateExtractionKey,
		arg.SourceQuery,
		arg.DataType,
		arg.DisplayName,
		arg.ID,
		arg.OrganizationID,
	)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.DataType,
		&i.CreatedAt,
		&i.DisplayName,
		&i.IsActive,
		&i.Category,
	)
	return i, err
}

const upsertExtractedDatum = `-- name: UpsertExtractedDatum :exec
INSERT INTO document_extracted_data (organization_id, document_id, key_id, extracted_value)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT uq_extracted_data_doc_key DO UPDATE
    SET extracted_value = EXCLUDED.extracted_value
`

type UpsertExtractedDatumParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	DocumentID     uuid.UUID   `json:"document_id"`
	KeyID          uuid.UUID   `json:"key_id"`
	ExtractedValue pgtype.Text `json:"extracted_value"`
}

// Idempotent upsert: inserts a single extracted key-value pair for a document.
// On conflict (organization_id, document_id, key_id) updates the value so repeated worker
// callbacks are safe and the latest value wins.
func (q *Queries) UpsertExtractedDatum(ctx context.Context, arg UpsertExtractedDatumParams) error {
	_, err := q.db.Exec(ctx, upsertExtractedDatum,
		arg.OrganizationID,
		arg.DocumentID,
		arg.KeyID,
		arg.ExtractedValue,
	)
	return err
}

const upsertExtractionKey = `-- name: UpsertExtractionKey :one
INSERT INTO extraction_keys (organization_id, key_name, source_query, data_type)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT ON CONSTRAINT uq_extraction_keys_org_name DO UPDATE
    SET source_query = EXCLUDED.source_query,
        data_type    = EXCLUDED.data_type
RETURNING id, organization_id, key_name, source_query, data_type, created_at, display_name, is_active, category
`

type UpsertExtractionKeyParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	KeyName        string      `json:"key_name"`
	SourceQuery    string      `json:"source_query"`
	DataType       string      `json:"data_type"`
}

// Idempotent upsert: on conflict (org, key_name), updates source_query and
// data_type so that RETURNING always yields the current row.
func (q *Queries) UpsertExtractionKey(ctx context.Context, arg UpsertExtractionKeyParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, upsertExtractionKey,
		arg.OrganizationID,
		arg.KeyName,
		arg.SourceQuery,
		arg.DataType,
	)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.DataType,
		&i.CreatedAt,
		&i.DisplayName,
		&i.IsActive,
		&i.Category,
	)
	return i, err
}
