// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extraction_request.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExtractionRequest = `-- name: CreateExtractionRequest :one
INSERT INTO extraction_requests (document_id, organization_id, questions, anonymize)
VALUES ($1, $2, $3, $4)
RETURNING id, document_id, organization_id, questions, anonymize, status, resolved_schema, error_message, created_at, updated_at
`

type CreateExtractionRequestParams struct {
	DocumentID     uuid.UUID       `json:"document_id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	Questions      json.RawMessage `json:"questions"`
	Anonymize      bool            `json:"anonymize"`
}

// Creates a new extraction request for a document. Tenant isolation is enforced
// by the composite FK (document_id, organization_id) → documents.
// Returns the created request including generated id and timestamps.
func (q *Queries) CreateExtractionRequest(ctx context.Context, arg CreateExtractionRequestParams) (ExtractionRequest, error) {
	row := q.db.QueryRow(ctx, createExtractionRequest,
		arg.DocumentID,
		arg.OrganizationID,
		arg.Questions,
		arg.Anonymize,
	)
	var i ExtractionRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Questions,
		&i.Anonymize,
		&i.Status,
		&i.ResolvedSchema,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExtractionRequest = `-- name: GetExtractionRequest :one
SELECT id, document_id, organization_id, questions, anonymize, status, resolved_schema, error_message, created_at, updated_at FROM extraction_requests
WHERE id = $1 AND organization_id = $2
`

type GetExtractionRequestParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Tenant-scoped lookup by id; callers should map pgx.ErrNoRows to 404.
func (q *Queries) GetExtractionRequest(ctx context.Context, arg GetExtractionRequestParams) (ExtractionRequest, error) {
	row := q.db.QueryRow(ctx, getExtractionRequest, arg.ID, arg.OrganizationID)
	var i ExtractionRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Questions,
		&i.Anonymize,
		&i.Status,
		&i.ResolvedSchema,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExtractionRequestByID = `-- name: GetExtractionRequestByID :one
SELECT id, document_id, organization_id, questions, anonymize, status, resolved_schema, error_message, created_at, updated_at FROM extraction_requests
WHERE id = $1
`

// Internal lookup without org check; callers (worker callbacks) must be
// authenticated via SERVICE_TOKEN and trust the id from a prior tenant-scoped
// write (document_tasks.extraction_request_id).
func (q *Queries) GetExtractionRequestByID(ctx context.Context, id uuid.UUID) (ExtractionRequest, error) {
	row := q.db.QueryRow(ctx, getExtractionRequestByID, id)
	var i ExtractionRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Questions,
		&i.Anonymize,
		&i.Status,
		&i.ResolvedSchema,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingExtractionRequestsByDocument = `-- name: ListPendingExtractionRequestsByDocument :many
SELECT id, document_id, organization_id, questions, anonymize, status, resolved_schema, error_message, created_at, updated_at FROM extraction_requests
WHERE document_id = $1
  AND status IN ('pending', 'running')
ORDER BY created_at ASC
`

// Returns extraction requests for a document that are still in flight
// (status pending or running). Used by WorkerService after prerequisite
// tasks (convert/anonymize) complete to progress all dependent requests.
func (q *Queries) ListPendingExtractionRequestsByDocument(ctx context.Context, documentID uuid.UUID) ([]ExtractionRequest, error) {
	rows, err := q.db.Query(ctx, listPendingExtractionRequestsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtractionRequest{}
	for rows.Next() {
		var i ExtractionRequest
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.OrganizationID,
			&i.Questions,
			&i.Anonymize,
			&i.Status,
			&i.ResolvedSchema,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExtractionRequestResolvedSchema = `-- name: SetExtractionRequestResolvedSchema :one
UPDATE extraction_requests
SET resolved_schema = $2,
    updated_at      = now()
WHERE id = $1
RETURNING id, document_id, organization_id, questions, anonymize, status, resolved_schema, error_message, created_at, updated_at
`

type SetExtractionRequestResolvedSchemaParams struct {
	ID             uuid.UUID `json:"id"`
	ResolvedSchema []byte    `json:"resolved_schema"`
}

// Stores resolved_schema returned by resolve_keys so the GET endpoint can
// enumerate which keys' answers belong to this request. Does not change status.
func (q *Queries) SetExtractionRequestResolvedSchema(ctx context.Context, arg SetExtractionRequestResolvedSchemaParams) (ExtractionRequest, error) {
	row := q.db.QueryRow(ctx, setExtractionRequestResolvedSchema, arg.ID, arg.ResolvedSchema)
	var i ExtractionRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Questions,
		&i.Anonymize,
		&i.Status,
		&i.ResolvedSchema,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setExtractionRequestStatus = `-- name: SetExtractionRequestStatus :one
UPDATE extraction_requests
SET status        = $2,
    error_message = COALESCE($3, error_message),
    updated_at    = now()
WHERE id = $1
RETURNING id, document_id, organization_id, questions, anonymize, status, resolved_schema, error_message, created_at, updated_at
`

type SetExtractionRequestStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

// Updates status (and optionally error_message) for a request.
// Used to transition pending → running on resolve_keys enqueue,
// running → completed when extract finishes,
// and pending|running → failed when a prerequisite task fails fatally.
func (q *Queries) SetExtractionRequestStatus(ctx context.Context, arg SetExtractionRequestStatusParams) (ExtractionRequest, error) {
	row := q.db.QueryRow(ctx, setExtractionRequestStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i ExtractionRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OrganizationID,
		&i.Questions,
		&i.Anonymize,
		&i.Status,
		&i.ResolvedSchema,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
