// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extraction.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExtractionKeysByNames = `-- name: GetExtractionKeysByNames :many
SELECT DISTINCT ON (key_name) id, organization_id, key_name, source_query, data_type, created_at FROM extraction_keys
WHERE key_name = ANY($1::text[])
  AND (organization_id = $2::uuid OR organization_id IS NULL)
ORDER BY key_name, (organization_id IS NULL) ASC
`

type GetExtractionKeysByNamesParams struct {
	KeyNames       []string  `json:"key_names"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

// Lookup extraction keys by key_name for a tenant. Returns org-specific keys
// and system keys (organization_id IS NULL) that match the given names.
// When both a tenant key and a system key share the same key_name, the tenant
// key is selected (DISTINCT ON + ORDER BY ensures deterministic precedence).
// Used in the extract callback to map key_name → key_id for bulk data insert.
func (q *Queries) GetExtractionKeysByNames(ctx context.Context, arg GetExtractionKeysByNamesParams) ([]ExtractionKey, error) {
	rows, err := q.db.Query(ctx, getExtractionKeysByNames, arg.KeyNames, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtractionKey{}
	for rows.Next() {
		var i ExtractionKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.KeyName,
			&i.SourceQuery,
			&i.DataType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtractionKeysByOrg = `-- name: ListExtractionKeysByOrg :many
SELECT id, organization_id, key_name, source_query, data_type, created_at FROM extraction_keys
WHERE organization_id = $1::uuid OR organization_id IS NULL
ORDER BY organization_id NULLS LAST, key_name
`

// Returns all keys visible to the given tenant: org-specific keys AND system
// keys (organization_id IS NULL) shared across all tenants.
func (q *Queries) ListExtractionKeysByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]ExtractionKey, error) {
	rows, err := q.db.Query(ctx, listExtractionKeysByOrg, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtractionKey{}
	for rows.Next() {
		var i ExtractionKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.KeyName,
			&i.SourceQuery,
			&i.DataType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExtractedDatum = `-- name: UpsertExtractedDatum :exec
INSERT INTO document_extracted_data (organization_id, document_id, key_id, extracted_value)
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT uq_extracted_data_doc_key DO UPDATE
    SET extracted_value = EXCLUDED.extracted_value
`

type UpsertExtractedDatumParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	DocumentID     uuid.UUID   `json:"document_id"`
	KeyID          uuid.UUID   `json:"key_id"`
	ExtractedValue pgtype.Text `json:"extracted_value"`
}

// Idempotent upsert: inserts a single extracted key-value pair for a document.
// On conflict (document_id, key_id) updates the value so repeated worker
// callbacks are safe and the latest value wins.
func (q *Queries) UpsertExtractedDatum(ctx context.Context, arg UpsertExtractedDatumParams) error {
	_, err := q.db.Exec(ctx, upsertExtractedDatum,
		arg.OrganizationID,
		arg.DocumentID,
		arg.KeyID,
		arg.ExtractedValue,
	)
	return err
}

const upsertExtractionKey = `-- name: UpsertExtractionKey :one
INSERT INTO extraction_keys (organization_id, key_name, source_query, data_type)
VALUES ($1::uuid, $2, $3, $4)
ON CONFLICT ON CONSTRAINT uq_extraction_keys_org_name DO UPDATE
    SET source_query = EXCLUDED.source_query,
        data_type    = EXCLUDED.data_type
RETURNING id, organization_id, key_name, source_query, data_type, created_at
`

type UpsertExtractionKeyParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	KeyName        string      `json:"key_name"`
	SourceQuery    string      `json:"source_query"`
	DataType       string      `json:"data_type"`
}

// Idempotent upsert: on conflict (org, key_name), updates source_query and
// data_type so that RETURNING always yields the current row.
func (q *Queries) UpsertExtractionKey(ctx context.Context, arg UpsertExtractionKeyParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, upsertExtractionKey,
		arg.OrganizationID,
		arg.KeyName,
		arg.SourceQuery,
		arg.DataType,
	)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.DataType,
		&i.CreatedAt,
	)
	return i, err
}
