// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: extraction_key.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExtractionKey = `-- name: CreateExtractionKey :one
INSERT INTO extraction_keys (organization_id, key_name, source_query, description, data_type, is_required)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, key_name, source_query, description, data_type, is_required, created_at, updated_at
`

type CreateExtractionKeyParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	KeyName        string      `json:"key_name"`
	SourceQuery    string      `json:"source_query"`
	Description    pgtype.Text `json:"description"`
	DataType       string      `json:"data_type"`
	IsRequired     bool        `json:"is_required"`
}

func (q *Queries) CreateExtractionKey(ctx context.Context, arg CreateExtractionKeyParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, createExtractionKey,
		arg.OrganizationID,
		arg.KeyName,
		arg.SourceQuery,
		arg.Description,
		arg.DataType,
		arg.IsRequired,
	)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.Description,
		&i.DataType,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentOrganizationID = `-- name: GetDocumentOrganizationID :one
SELECT organization_id
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentOrganizationID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDocumentOrganizationID, id)
	var organization_id uuid.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const getExtractionKeyByOrgAndKeyName = `-- name: GetExtractionKeyByOrgAndKeyName :one
SELECT id, organization_id, key_name, source_query, description, data_type, is_required, created_at, updated_at
FROM extraction_keys
WHERE organization_id IS NOT DISTINCT FROM $1
  AND key_name = $2
`

type GetExtractionKeyByOrgAndKeyNameParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	KeyName        string      `json:"key_name"`
}

func (q *Queries) GetExtractionKeyByOrgAndKeyName(ctx context.Context, arg GetExtractionKeyByOrgAndKeyNameParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, getExtractionKeyByOrgAndKeyName, arg.OrganizationID, arg.KeyName)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.Description,
		&i.DataType,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExtractionKeyByOrgAndSourceQuery = `-- name: GetExtractionKeyByOrgAndSourceQuery :one
SELECT id, organization_id, key_name, source_query, description, data_type, is_required, created_at, updated_at
FROM extraction_keys
WHERE organization_id IS NOT DISTINCT FROM $1
  AND lower(btrim(source_query)) = lower(btrim($2))
ORDER BY created_at ASC
LIMIT 1
`

type GetExtractionKeyByOrgAndSourceQueryParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SourceQuery    string      `json:"source_query"`
}

func (q *Queries) GetExtractionKeyByOrgAndSourceQuery(ctx context.Context, arg GetExtractionKeyByOrgAndSourceQueryParams) (ExtractionKey, error) {
	row := q.db.QueryRow(ctx, getExtractionKeyByOrgAndSourceQuery, arg.OrganizationID, arg.SourceQuery)
	var i ExtractionKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyName,
		&i.SourceQuery,
		&i.Description,
		&i.DataType,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExtractionKeyPayloadsByOrganization = `-- name: ListExtractionKeyPayloadsByOrganization :many
SELECT id, key_name, source_query, description, data_type, is_required
FROM extraction_keys
WHERE organization_id IS NOT DISTINCT FROM $1
ORDER BY created_at ASC
`

type ListExtractionKeyPayloadsByOrganizationRow struct {
	ID          uuid.UUID   `json:"id"`
	KeyName     string      `json:"key_name"`
	SourceQuery string      `json:"source_query"`
	Description pgtype.Text `json:"description"`
	DataType    string      `json:"data_type"`
	IsRequired  bool        `json:"is_required"`
}

func (q *Queries) ListExtractionKeyPayloadsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListExtractionKeyPayloadsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listExtractionKeyPayloadsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExtractionKeyPayloadsByOrganizationRow{}
	for rows.Next() {
		var i ListExtractionKeyPayloadsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyName,
			&i.SourceQuery,
			&i.Description,
			&i.DataType,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtractionKeysByOrganization = `-- name: ListExtractionKeysByOrganization :many
SELECT id, organization_id, key_name, source_query, description, data_type, is_required, created_at, updated_at
FROM extraction_keys
WHERE organization_id IS NOT DISTINCT FROM $1
ORDER BY created_at ASC
`

func (q *Queries) ListExtractionKeysByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ExtractionKey, error) {
	rows, err := q.db.Query(ctx, listExtractionKeysByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExtractionKey{}
	for rows.Next() {
		var i ExtractionKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.KeyName,
			&i.SourceQuery,
			&i.Description,
			&i.DataType,
			&i.IsRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocumentExtractedData = `-- name: UpsertDocumentExtractedData :one
INSERT INTO document_extracted_data (organization_id, document_id, key_id, extracted_value, confidence)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (document_id, key_id)
DO UPDATE SET
    extracted_value = EXCLUDED.extracted_value,
    confidence      = EXCLUDED.confidence,
    updated_at      = now()
RETURNING id, organization_id, document_id, key_id, extracted_value, confidence, created_at, updated_at
`

type UpsertDocumentExtractedDataParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	DocumentID     uuid.UUID       `json:"document_id"`
	KeyID          uuid.UUID       `json:"key_id"`
	ExtractedValue json.RawMessage `json:"extracted_value"`
	Confidence     pgtype.Float8   `json:"confidence"`
}

func (q *Queries) UpsertDocumentExtractedData(ctx context.Context, arg UpsertDocumentExtractedDataParams) (DocumentExtractedDatum, error) {
	row := q.db.QueryRow(ctx, upsertDocumentExtractedData,
		arg.OrganizationID,
		arg.DocumentID,
		arg.KeyID,
		arg.ExtractedValue,
		arg.Confidence,
	)
	var i DocumentExtractedDatum
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DocumentID,
		&i.KeyID,
		&i.ExtractedValue,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
