// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_role.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFileRole = `-- name: CreateFileRole :one
INSERT INTO document_file_roles (organization_id, display_name, sort_order, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, display_name, sort_order, is_active, created_at, updated_at
`

type CreateFileRoleParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	DisplayName    string      `json:"display_name"`
	SortOrder      int16       `json:"sort_order"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) CreateFileRole(ctx context.Context, arg CreateFileRoleParams) (DocumentFileRole, error) {
	row := q.db.QueryRow(ctx, createFileRole,
		arg.OrganizationID,
		arg.DisplayName,
		arg.SortOrder,
		arg.IsActive,
	)
	var i DocumentFileRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFileRole = `-- name: DeleteFileRole :execrows
DELETE FROM document_file_roles
WHERE id = $1 AND organization_id = $2
`

type DeleteFileRoleParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteFileRole(ctx context.Context, arg DeleteFileRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileRole, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFileRole = `-- name: GetFileRole :one
SELECT id, organization_id, display_name, sort_order, is_active, created_at, updated_at FROM document_file_roles
WHERE id = $1
  AND (organization_id = $2::uuid OR organization_id IS NULL)
`

type GetFileRoleParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) GetFileRole(ctx context.Context, arg GetFileRoleParams) (DocumentFileRole, error) {
	row := q.db.QueryRow(ctx, getFileRole, arg.ID, arg.Column2)
	var i DocumentFileRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFileRolesByOrg = `-- name: ListFileRolesByOrg :many
SELECT id, organization_id, display_name, sort_order, is_active, created_at, updated_at FROM document_file_roles
WHERE organization_id = $1::uuid OR organization_id IS NULL
ORDER BY sort_order ASC, display_name ASC
`

// Returns all file roles visible to the given tenant: org-specific AND system roles (organization_id IS NULL).
func (q *Queries) ListFileRolesByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]DocumentFileRole, error) {
	rows, err := q.db.Query(ctx, listFileRolesByOrg, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentFileRole{}
	for rows.Next() {
		var i DocumentFileRole
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.DisplayName,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileRole = `-- name: UpdateFileRole :one
UPDATE document_file_roles
SET display_name = $3,
    sort_order   = $4,
    is_active    = $5,
    updated_at   = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, display_name, sort_order, is_active, created_at, updated_at
`

type UpdateFileRoleParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	DisplayName    string      `json:"display_name"`
	SortOrder      int16       `json:"sort_order"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateFileRole(ctx context.Context, arg UpdateFileRoleParams) (DocumentFileRole, error) {
	row := q.db.QueryRow(ctx, updateFileRole,
		arg.ID,
		arg.OrganizationID,
		arg.DisplayName,
		arg.SortOrder,
		arg.IsActive,
	)
	var i DocumentFileRole
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.DisplayName,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
