// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Сохранённые сессии сравнения договоров; восстанавливаются по /compare?session=:id
type ComparisonSession struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
	// Человекочитаемое название сессии; NULL — автогенерация в UI
	Name pgtype.Text `json:"name"`
	// Тип договора, по которому выполнялось сравнение; NULL если тип был удалён
	ContractKindID pgtype.UUID `json:"contract_kind_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

// Документы, участвующие в сессии сравнения
type ComparisonSessionDocument struct {
	SessionID  uuid.UUID `json:"session_id"`
	DocumentID uuid.UUID `json:"document_id"`
	// Тенант; денормализован для composite FK-защиты (→ documents)
	OrganizationID uuid.UUID `json:"organization_id"`
	// Порядок столбца в таблице сравнения; 0-based
	Position int16 `json:"position"`
}

// Объекты строительства (ЖК, очереди, корпуса) — иерархическая структура тенанта
type ConstructionSite struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	// ID родительского объекта; NULL для корневых объектов (например, сам ЖК)
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	// Статус жизненного цикла: active | completed | archived
	Status string `json:"status"`
	// Пользователь, создавший объект; NULL если пользователь удалён
	CreatedBy pgtype.UUID `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	// Путь к обложке объекта в MinIO; NULL — плейсхолдер
	CoverImagePath pgtype.Text `json:"cover_image_path"`
	// Время последней загрузки обложки
	CoverImageUploadedAt pgtype.Timestamptz `json:"cover_image_uploaded_at"`
	// Тип объекта: residential_complex | business_center | warehouse | phase | building | section | other; NULL если не указан
	SiteType pgtype.Text `json:"site_type"`
	// Время последней активности в объекте или любом его потомке; обновляется триггером
	LastActivityAt time.Time `json:"last_activity_at"`
}

// Метаданные загруженных файлов и AI-артефактов; физические файлы — в MinIO
type Document struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	// Объект строительства документа; NULL — документ без привязки к объекту
	SiteID     pgtype.UUID `json:"site_id"`
	UploadedBy uuid.UUID   `json:"uploaded_by"`
	// Исходный документ, если запись является артефактом воркера; NULL для оригиналов
	ParentID pgtype.UUID `json:"parent_id"`
	FileName string      `json:"file_name"`
	// Путь к файлу в MinIO: bucket/prefix/uuid.ext
	StoragePath string `json:"storage_path"`
	// MIME-тип файла, определяется при загрузке; NULL если не определён
	MimeType pgtype.Text `json:"mime_type"`
	// Размер файла в байтах; NULL если не известен на момент создания записи
	FileSizeBytes pgtype.Int8 `json:"file_size_bytes"`
	// Тип артефакта: NULL — загружен пользователем; convert_md — результат конвертации в Markdown; anonymize_doc — анонимизированный документ; anonymize_entities — карта сущностей анонимизации
	ArtifactKind pgtype.Text `json:"artifact_kind"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	// Тип договора из справочника document_contract_kinds; NULL для артефактов воркера
	ContractKindID pgtype.UUID `json:"contract_kind_id"`
	// Роль файла в комплекте из справочника document_file_roles; NULL для артефактов воркера
	FileRoleID pgtype.UUID `json:"file_role_id"`
	// Корневой документ комплекта; NULL — документ является корнем или не входит в комплект; артефакты воркера всегда NULL
	BundleID pgtype.UUID `json:"bundle_id"`
}

// Справочник типов договоров; управляется тенантом
type DocumentContractKind struct {
	ID uuid.UUID `json:"id"`
	// NULL — системная запись, видна всем тенантам; NOT NULL — запись конкретного тенанта
	OrganizationID pgtype.UUID `json:"organization_id"`
	// Человекочитаемое название: «Генподряд», «Стройконтроль», «Отделка» …
	DisplayName string `json:"display_name"`
	// Порядок отображения в UI; меньше — выше
	SortOrder int16 `json:"sort_order"`
	// false — тип скрыт из выпадающих списков; существующие документы не затрагиваются
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Извлечённые значения ключей для конкретного документа
type DocumentExtractedDatum struct {
	ID uuid.UUID `json:"id"`
	// Тенант; денормализован для composite FK-защиты (→ documents)
	OrganizationID uuid.UUID `json:"organization_id"`
	// Документ, из которого извлечены данные
	DocumentID uuid.UUID `json:"document_id"`
	// Ключ извлечения
	KeyID uuid.UUID `json:"key_id"`
	// Извлечённое значение; NULL если воркер не смог извлечь
	ExtractedValue pgtype.Text `json:"extracted_value"`
}

// Справочник ролей файлов внутри комплекта договора; управляется тенантом
type DocumentFileRole struct {
	ID uuid.UUID `json:"id"`
	// NULL — системная запись, видна всем тенантам; NOT NULL — запись конкретного тенанта
	OrganizationID pgtype.UUID `json:"organization_id"`
	// Человекочитаемое название: «Основной договор», «Смета», «ТЗ», «Матрица ответственности» …
	DisplayName string `json:"display_name"`
	// Порядок отображения в UI; меньше — выше
	SortOrder int16 `json:"sort_order"`
	// false — роль скрыта из выпадающих списков; существующие документы не затрагиваются
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Задачи AI-воркера на Python для обработки документов
type DocumentTask struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	// Маршрутизатор воркера: определяет логику обработки (convert, anonymize, parse_invoice, extract и др.)
	ModuleName string `json:"module_name"`
	// Статус выполнения: pending | processing | completed | failed
	Status string `json:"status"`
	// UUID задачи в Celery; заполняется воркером при взятии задачи в работу
	CeleryTaskID pgtype.Text `json:"celery_task_id"`
	// Структурированный результат обработки; схема зависит от module_name
	ResultPayload json.RawMessage `json:"result_payload"`
	// Описание ошибки при status = failed; NULL в остальных случаях
	ErrorMessage pgtype.Text `json:"error_message"`
	// Число перезапусков watchdog-ом; при превышении WatchdogMaxRetries задача переводится в failed
	RetryCount int32 `json:"retry_count"`
	// Путь к входному файлу воркера в MinIO; определяется модулем и фиксируется при создании задачи
	InputStoragePath string    `json:"input_storage_path"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	// Запрос экстракции, к которому относится таска. NULL для convert/anonymize (singleton документа); NOT NULL для resolve_keys/extract.
	ExtractionRequestID pgtype.UUID `json:"extraction_request_id"`
}

// Ключи для семантического извлечения данных из документов
type ExtractionKey struct {
	ID uuid.UUID `json:"id"`
	// NULL — системный ключ (общий для всех тенантов); NOT NULL — ключ конкретного тенанта
	OrganizationID pgtype.UUID `json:"organization_id"`
	// Машинное имя ключа (латиница + подчёркивание, макс. 50 симв.)
	KeyName string `json:"key_name"`
	// Исходный вопрос на естественном языке, на основе которого создан ключ
	SourceQuery string `json:"source_query"`
	// Тип значения: string | number | date | boolean
	DataType  string    `json:"data_type"`
	CreatedAt time.Time `json:"created_at"`
	// Человекочитаемое имя параметра для UI; NULL — fallback на source_query или key_name
	DisplayName pgtype.Text `json:"display_name"`
	// false — ключ скрыт из UI, данные в document_extracted_data сохранены
	IsActive bool `json:"is_active"`
	// Смысловая группа: commercial | volumetric | legal | other; NULL — без группировки
	Category pgtype.Text `json:"category"`
}

// Пользовательский запрос на извлечение данных из документа (один комплект вопросов)
type ExtractionRequest struct {
	ID             uuid.UUID `json:"id"`
	DocumentID     uuid.UUID `json:"document_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	// Массив строк-вопросов на естественном языке (jsonb array)
	Questions json.RawMessage `json:"questions"`
	// true — extract читает анонимизированный артефакт; false — читает markdown-артефакт
	Anonymize bool `json:"anonymize"`
	// pending — ждёт prereq-задач; running — resolve_keys/extract в работе; completed — ответы готовы; failed — ошибка
	Status string `json:"status"`
	// JSON-схема ключей, возвращённая resolve_keys; используется для выборки ответов из document_extracted_data
	ResolvedSchema []byte      `json:"resolved_schema"`
	ErrorMessage   pgtype.Text `json:"error_message"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

// Организации — изолированные тенанты системы
type Organization struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	// ИНН: 10 цифр для ЮЛ, 12 для ИП; NULL если не указан
	Inn pgtype.Text `json:"inn"`
	// Произвольные настройки тенанта (тема, лимиты, флаги)
	Settings json.RawMessage `json:"settings"`
	// false — организация деактивирована, вход для всех её пользователей заблокирован
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Лог событий объекта для вкладки «История» и блока «Последняя активность»
type SiteAuditLog struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	// Объект, в котором произошло событие (всегда конечный объект, не родитель)
	SiteID uuid.UUID `json:"site_id"`
	// Инициатор события; NULL для системных событий (watchdog, воркер)
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	// Тип события; словарь расширяется приложением без миграции
	EventType string `json:"event_type"`
	// Контекст события; схема зависит от event_type
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

// Пользователи, привязанные к организации
type User struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
	PasswordHash   string    `json:"password_hash"`
	FullName       string    `json:"full_name"`
	// Роль пользователя: admin — полный доступ к тенанту, member — работа с документами
	Role string `json:"role"`
	// false — пользователь деактивирован, вход заблокирован
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// Время последнего успешного входа; NULL если пользователь ещё не входил
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

// Pending-приглашения пользователей в организацию; токен отправляется на email
type UserInvitation struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Email          string      `json:"email"`
	Role           string      `json:"role"`
	InvitedBy      pgtype.UUID `json:"invited_by"`
	// Хэш одноразового токена из письма; сам токен не хранится
	TokenHash string `json:"token_hash"`
	// Срок действия приглашения; после истечения токен невалиден
	ExpiresAt time.Time `json:"expires_at"`
	// Время принятия; NULL — приглашение ещё не принято
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

// Рекурсивный агрегат статуса объекта по всему поддереву. Одна строка на каждый объект (корневой, промежуточный, конечный). children_* — количество листьев поддерева в каждом статусе. Для конечного объекта ровно один счётчик равен 1.
type VSiteStatus struct {
	SiteID             uuid.UUID `json:"site_id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	Status             string    `json:"status"`
	ChildrenReady      int64     `json:"children_ready"`
	ChildrenProcessing int64     `json:"children_processing"`
	ChildrenAttention  int64     `json:"children_attention"`
	ChildrenEmpty      int64     `json:"children_empty"`
}
