// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Объекты строительства (ЖК, очереди, корпуса) — иерархическая структура тенанта
type ConstructionSite struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	// ID родительского объекта; NULL для корневых объектов (например, сам ЖК)
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	// Статус жизненного цикла: active | completed | archived
	Status string `json:"status"`
	// Пользователь, создавший объект; NULL если пользователь удалён
	CreatedBy pgtype.UUID `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// Метаданные загруженных файлов и AI-артефактов; физические файлы — в MinIO
type Document struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	// Объект строительства документа; NULL — документ без привязки к объекту
	SiteID     pgtype.UUID `json:"site_id"`
	UploadedBy uuid.UUID   `json:"uploaded_by"`
	// Исходный документ, если запись является артефактом воркера; NULL для оригиналов
	ParentID pgtype.UUID `json:"parent_id"`
	FileName string      `json:"file_name"`
	// Путь к файлу в MinIO: bucket/prefix/uuid.ext
	StoragePath string `json:"storage_path"`
	// MIME-тип файла, определяется при загрузке; NULL если не определён
	MimeType pgtype.Text `json:"mime_type"`
	// Размер файла в байтах; NULL если не известен на момент создания записи
	FileSizeBytes pgtype.Int8 `json:"file_size_bytes"`
	// Тип артефакта: NULL — загружен пользователем; convert_md — результат конвертации в Markdown; anonymize_doc — анонимизированный документ; anonymize_entities — карта сущностей анонимизации
	ArtifactKind pgtype.Text `json:"artifact_kind"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

// Задачи AI-воркера на Python для обработки документов
type DocumentTask struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	// Маршрутизатор воркера: определяет логику обработки (convert, anonymize, parse_invoice, extract и др.)
	ModuleName string `json:"module_name"`
	// Статус выполнения: pending | processing | completed | failed
	Status string `json:"status"`
	// UUID задачи в Celery; заполняется воркером при взятии задачи в работу
	CeleryTaskID pgtype.Text `json:"celery_task_id"`
	// Структурированный результат обработки; схема зависит от module_name
	ResultPayload json.RawMessage `json:"result_payload"`
	// Описание ошибки при status = failed; NULL в остальных случаях
	ErrorMessage pgtype.Text `json:"error_message"`
	// Число перезапусков watchdog-ом; при превышении WatchdogMaxRetries задача переводится в failed
	RetryCount int32 `json:"retry_count"`
	// Путь к входному файлу воркера в MinIO; определяется модулем и фиксируется при создании задачи
	InputStoragePath string    `json:"input_storage_path"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// Организации — изолированные тенанты системы
type Organization struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	// ИНН: 10 цифр для ЮЛ, 12 для ИП; NULL если не указан
	Inn pgtype.Text `json:"inn"`
	// Произвольные настройки тенанта (тема, лимиты, флаги)
	Settings json.RawMessage `json:"settings"`
	// false — организация деактивирована, вход для всех её пользователей заблокирован
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Пользователи, привязанные к организации
type User struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
	PasswordHash   string    `json:"password_hash"`
	FullName       string    `json:"full_name"`
	// Роль пользователя: admin — полный доступ к тенанту, member — работа с документами
	Role string `json:"role"`
	// false — пользователь деактивирован, вход заблокирован
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
