// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, inn)
VALUES ($1, $2)
RETURNING id, name, inn, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string      `json:"name"`
	Inn  pgtype.Text `json:"inn"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Inn)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Inn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :execrows
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrganization, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, inn, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Inn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByINN = `-- name: GetOrganizationByINN :one
SELECT id, name, inn, created_at, updated_at FROM organizations WHERE inn = $1
`

func (q *Queries) GetOrganizationByINN(ctx context.Context, inn pgtype.Text) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByINN, inn)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Inn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name       = $2,
    inn        = CASE WHEN $4::boolean THEN $3 ELSE inn END,
    updated_at = now()
WHERE id = $1
RETURNING id, name, inn, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	Inn     pgtype.Text `json:"inn"`
	Column4 bool        `json:"column_4"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Inn,
		arg.Column4,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Inn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
