// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptUserInvitation(ctx context.Context, id uuid.UUID) (UserInvitation, error)
	AddDocumentToComparisonSession(ctx context.Context, arg AddDocumentToComparisonSessionParams) (ComparisonSessionDocument, error)
	// Batch idempotent upsert: inserts all extracted key-value pairs for a document
	// in a single statement. Two unnest() calls in the SELECT list are expanded
	// in lockstep by PostgreSQL (guaranteed since PG 10), zipping key_ids with
	// extracted_values row-by-row. FROM unnest(arr, arr) would be cleaner but
	// sqlc does not support multi-arg unnest in the FROM clause. On conflict,
	// latest value wins.
	BatchUpsertExtractedData(ctx context.Context, arg BatchUpsertExtractedDataParams) error
	// Idempotent artifact creation: on conflict (parent_id, artifact_kind) updates
	// artifact metadata from the latest callback so that RETURNING yields the current row state.
	// Prevents duplicate artifact documents when a worker sends a duplicate 'completed' callback.
	CreateArtifactDocument(ctx context.Context, arg CreateArtifactDocumentParams) (Document, error)
	CreateComparisonSession(ctx context.Context, arg CreateComparisonSessionParams) (ComparisonSession, error)
	CreateConstructionSite(ctx context.Context, arg CreateConstructionSiteParams) (ConstructionSite, error)
	CreateContractKind(ctx context.Context, arg CreateContractKindParams) (DocumentContractKind, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	// Public API: only 'convert' tasks may be created here; the input is always the
	// original document's storage_path. Other modules (e.g. anonymize) read a derived
	// artifact path and must be created internally via CreateDocumentTaskInternal.
	// Callers MUST map pgx.ErrNoRows to 404: the INSERT ... SELECT returns no rows
	// when the document is missing or belongs to another organization, and this is
	// intentionally reported as 404 to avoid leaking tenant existence. This is
	// distinct from unique-constraint violations on (document_id, module_name).
	CreateDocumentTask(ctx context.Context, arg CreateDocumentTaskParams) (DocumentTask, error)
	// Internal: creates a per-request task (resolve_keys/extract) bound to an
	// extraction_request. Idempotent via partial index uq_document_tasks_request_module —
	// duplicate (extraction_request_id, module_name) returns pgx.ErrNoRows.
	// $4 is the extraction_request_id; $3 is input_storage_path.
	CreateDocumentTaskForRequest(ctx context.Context, arg CreateDocumentTaskForRequestParams) (DocumentTask, error)
	// Internal: creates a singleton task (convert/anonymize) for a document.
	// Idempotent via partial index uq_document_tasks_doc_singleton — duplicate
	// (document_id, module_name) on convert/anonymize returns pgx.ErrNoRows.
	// $3 is input_storage_path: the file path the Python worker will receive for this module.
	// extraction_request_id is intentionally NULL; convert/anonymize artifacts are
	// per-document and reused across all extraction_requests on the same document.
	CreateDocumentTaskSingleton(ctx context.Context, arg CreateDocumentTaskSingletonParams) (DocumentTask, error)
	// Creates a new extraction request for a document. Tenant isolation is enforced
	// by the composite FK (document_id, organization_id) → documents.
	// Returns the created request including generated id and timestamps.
	CreateExtractionRequest(ctx context.Context, arg CreateExtractionRequestParams) (ExtractionRequest, error)
	CreateFileRole(ctx context.Context, arg CreateFileRoleParams) (DocumentFileRole, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateSiteAuditEvent(ctx context.Context, arg CreateSiteAuditEventParams) (SiteAuditLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (UserInvitation, error)
	DeleteComparisonSession(ctx context.Context, arg DeleteComparisonSessionParams) (int64, error)
	DeleteConstructionSite(ctx context.Context, arg DeleteConstructionSiteParams) (int64, error)
	DeleteContractKind(ctx context.Context, arg DeleteContractKindParams) (int64, error)
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int64, error)
	DeleteDocumentTask(ctx context.Context, arg DeleteDocumentTaskParams) (int64, error)
	DeleteFileRole(ctx context.Context, arg DeleteFileRoleParams) (int64, error)
	DeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteUserInvitation(ctx context.Context, arg DeleteUserInvitationParams) (int64, error)
	GetComparisonSession(ctx context.Context, arg GetComparisonSessionParams) (ComparisonSession, error)
	GetConstructionSite(ctx context.Context, arg GetConstructionSiteParams) (ConstructionSite, error)
	GetContractKind(ctx context.Context, arg GetContractKindParams) (DocumentContractKind, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
	// WARNING: This lookup is intentionally unscoped by organization_id.
	// Callers MUST enforce organization isolation at the service layer.
	// Prefer GetDocument when organization-scoped access is required.
	GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentTask(ctx context.Context, arg GetDocumentTaskParams) (DocumentTask, error)
	// Lookup extraction keys by key_name for a tenant. Returns org-specific keys
	// and system keys (organization_id IS NULL) that match the given names.
	// When both a tenant key and a system key share the same key_name, the tenant
	// key is selected (DISTINCT ON + ORDER BY ensures deterministic precedence).
	// Used in the extract callback to map key_name → key_id for bulk data insert.
	GetExtractionKeysByNames(ctx context.Context, arg GetExtractionKeysByNamesParams) ([]ExtractionKey, error)
	// Tenant-scoped lookup by id; callers should map pgx.ErrNoRows to 404.
	GetExtractionRequest(ctx context.Context, arg GetExtractionRequestParams) (ExtractionRequest, error)
	// Internal lookup without org check; callers (worker callbacks) must be
	// authenticated via SERVICE_TOKEN and trust the id from a prior tenant-scoped
	// write (document_tasks.extraction_request_id).
	GetExtractionRequestByID(ctx context.Context, id uuid.UUID) (ExtractionRequest, error)
	GetFileRole(ctx context.Context, arg GetFileRoleParams) (DocumentFileRole, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByINN(ctx context.Context, inn pgtype.Text) (Organization, error)
	// Returns the singleton convert/anonymize task for a document, if it exists.
	// Used to inspect the current state of prerequisite tasks before deciding
	// what to enqueue next for an extraction_request.
	GetSingletonTaskByDocument(ctx context.Context, arg GetSingletonTaskByDocumentParams) (DocumentTask, error)
	GetSiteStatus(ctx context.Context, arg GetSiteStatusParams) (VSiteStatus, error)
	// Returns a per-request task (resolve_keys/extract) for the given extraction_request.
	GetTaskForExtractionRequest(ctx context.Context, arg GetTaskForExtractionRequestParams) (DocumentTask, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIDAndOrg(ctx context.Context, arg GetUserByIDAndOrgParams) (GetUserByIDAndOrgRow, error)
	GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error)
	ListComparisonSessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]ComparisonSessionDocument, error)
	ListComparisonSessionsByOrg(ctx context.Context, organizationID uuid.UUID) ([]ComparisonSession, error)
	ListConstructionSitesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ConstructionSite, error)
	ListConstructionSitesByParent(ctx context.Context, arg ListConstructionSitesByParentParams) ([]ConstructionSite, error)
	// Returns all contract kinds visible to the given tenant: org-specific AND system kinds (organization_id IS NULL).
	ListContractKindsByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]DocumentContractKind, error)
	// Все артефакты, порождённые данным документом; scoped by organization_id for tenant isolation.
	ListDocumentsByParent(ctx context.Context, arg ListDocumentsByParentParams) ([]Document, error)
	// Returns extracted values for a document filtered to the given extraction
	// keys, joined with key metadata. Tenant-scoped: only data and keys visible
	// to the given organization (org-specific keys + system keys) are returned.
	// Used by GET /extraction-requests/:id to assemble the answers map for a
	// specific request's resolved_schema.
	ListExtractedDataForKeys(ctx context.Context, arg ListExtractedDataForKeysParams) ([]ListExtractedDataForKeysRow, error)
	// Returns all keys visible to the given tenant: org-specific keys AND system
	// keys (organization_id IS NULL) shared across all tenants.
	ListExtractionKeysByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]ExtractionKey, error)
	// Returns all file roles visible to the given tenant: org-specific AND system roles (organization_id IS NULL).
	ListFileRolesByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]DocumentFileRole, error)
	// Returns extraction requests for a document that are still in flight
	// (status pending or running). Used by WorkerService after prerequisite
	// tasks (convert/anonymize) complete to progress all dependent requests.
	ListPendingExtractionRequestsByDocument(ctx context.Context, documentID uuid.UUID) ([]ExtractionRequest, error)
	ListRootConstructionSites(ctx context.Context, organizationID uuid.UUID) ([]ConstructionSite, error)
	// Только корневые документы (загруженные пользователем, не артефакты)
	ListRootDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Document, error)
	ListRootDocumentsBySite(ctx context.Context, arg ListRootDocumentsBySiteParams) ([]Document, error)
	ListSiteAuditLogBySite(ctx context.Context, arg ListSiteAuditLogBySiteParams) ([]SiteAuditLog, error)
	ListSiteStatusesByOrg(ctx context.Context, organizationID uuid.UUID) ([]VSiteStatus, error)
	// Watchdog: returns stuck tasks (pending or processing) whose updated_at is older than
	// sqlc.arg(cutoff). Results are limited by sqlc.arg(batch_size). Uses
	// dt.input_storage_path so the correct file path is returned for every module:
	// 'convert' tasks get the original document path, 'anonymize' tasks get the
	// convert_md artifact path (stored at task creation time).
	// Covers two failure modes: worker died mid-processing (processing) and
	// Redis message was lost before worker picked it up (pending).
	// No org-check; caller must be trusted (watchdog goroutine only).
	ListStaleTasks(ctx context.Context, arg ListStaleTasksParams) ([]ListStaleTasksRow, error)
	ListTasksByDocument(ctx context.Context, arg ListTasksByDocumentParams) ([]DocumentTask, error)
	ListTasksByDocuments(ctx context.Context, arg ListTasksByDocumentsParams) ([]DocumentTask, error)
	ListUserInvitationsByOrg(ctx context.Context, organizationID uuid.UUID) ([]UserInvitation, error)
	ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListUsersByOrganizationRow, error)
	// Watchdog: permanently fails a task that has exhausted all retry attempts.
	// updated_at < cutoff prevents failing a task that was refreshed after ListStaleTasks.
	MarkStaleTaskFailed(ctx context.Context, arg MarkStaleTaskFailedParams) (int64, error)
	// Watchdog: atomically resets a stale task to pending and increments retry_count.
	// The WHERE status IN (...) AND updated_at < cutoff guard makes this a true
	// compare-and-swap on both status and staleness: two concurrent watchdog instances
	// cannot double-claim the same task, and a task that was refreshed between
	// ListStaleTasks and this UPDATE will not be incorrectly reset.
	MarkStaleTaskPending(ctx context.Context, arg MarkStaleTaskPendingParams) (int64, error)
	RemoveDocumentFromComparisonSession(ctx context.Context, arg RemoveDocumentFromComparisonSessionParams) (int64, error)
	// Stores resolved_schema returned by resolve_keys so the GET endpoint can
	// enumerate which keys' answers belong to this request. Does not change status.
	SetExtractionRequestResolvedSchema(ctx context.Context, arg SetExtractionRequestResolvedSchemaParams) (ExtractionRequest, error)
	// Updates status (and optionally error_message) for a request.
	// Used to transition pending → running on resolve_keys enqueue,
	// running → completed when extract finishes,
	// and pending|running → failed when a prerequisite task fails fatally.
	SetExtractionRequestStatus(ctx context.Context, arg SetExtractionRequestStatusParams) (ExtractionRequest, error)
	UpdateConstructionSite(ctx context.Context, arg UpdateConstructionSiteParams) (ConstructionSite, error)
	UpdateConstructionSiteCover(ctx context.Context, arg UpdateConstructionSiteCoverParams) (ConstructionSite, error)
	UpdateConstructionSiteType(ctx context.Context, arg UpdateConstructionSiteTypeParams) (ConstructionSite, error)
	UpdateContractKind(ctx context.Context, arg UpdateContractKindParams) (DocumentContractKind, error)
	// Updates document classification fields (contract_kind, file_role, bundle).
	// Only applicable to root documents (parent_id IS NULL); artifacts are excluded by DB constraint.
	UpdateDocumentMeta(ctx context.Context, arg UpdateDocumentMetaParams) (Document, error)
	UpdateDocumentTaskStatus(ctx context.Context, arg UpdateDocumentTaskStatusParams) (DocumentTask, error)
	UpdateFileRole(ctx context.Context, arg UpdateFileRoleParams) (DocumentFileRole, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	// Internal: no org-check; callers must be authenticated via SERVICE_TOKEN.
	// Updates result_payload only; does not change status, celery_task_id, or error_message.
	// Used by WorkerService after registering artifacts so updated_at is touched
	// only for payload changes, not for status semantics.
	UpdateTaskResultPayload(ctx context.Context, arg UpdateTaskResultPayloadParams) (DocumentTask, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	// Internal: no org-check; callers must be authenticated via SERVICE_TOKEN.
	UpdateWorkerTaskStatus(ctx context.Context, arg UpdateWorkerTaskStatusParams) (DocumentTask, error)
	// Idempotent upsert: inserts a single extracted key-value pair for a document.
	// On conflict (organization_id, document_id, key_id) updates the value so repeated worker
	// callbacks are safe and the latest value wins.
	UpsertExtractedDatum(ctx context.Context, arg UpsertExtractedDatumParams) error
	// Idempotent upsert: on conflict (org, key_name), updates source_query and
	// data_type so that RETURNING always yields the current row.
	UpsertExtractionKey(ctx context.Context, arg UpsertExtractionKeyParams) (ExtractionKey, error)
}

var _ Querier = (*Queries)(nil)
