// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	// ── Document Tasks ──────────────────────────────────
	CreateDocumentTask(ctx context.Context, arg CreateDocumentTaskParams) (DocumentTask, error)
	DeleteDocument(ctx context.Context, id uuid.UUID) error
	DeleteDocumentTask(ctx context.Context, id uuid.UUID) error
	GetDocument(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentTask(ctx context.Context, id uuid.UUID) (DocumentTask, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Document, error)
	ListTasksByDocument(ctx context.Context, documentID uuid.UUID) ([]DocumentTask, error)
	UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error)
	UpdateDocumentTaskStatus(ctx context.Context, arg UpdateDocumentTaskStatusParams) (DocumentTask, error)
}

var _ Querier = (*Queries)(nil)
