// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_status.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getSiteStatus = `-- name: GetSiteStatus :one
SELECT site_id, organization_id, status, children_ready, children_processing, children_attention, children_empty FROM v_site_status
WHERE site_id = $1 AND organization_id = $2
`

type GetSiteStatusParams struct {
	SiteID         uuid.UUID `json:"site_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetSiteStatus(ctx context.Context, arg GetSiteStatusParams) (VSiteStatus, error) {
	row := q.db.QueryRow(ctx, getSiteStatus, arg.SiteID, arg.OrganizationID)
	var i VSiteStatus
	err := row.Scan(
		&i.SiteID,
		&i.OrganizationID,
		&i.Status,
		&i.ChildrenReady,
		&i.ChildrenProcessing,
		&i.ChildrenAttention,
		&i.ChildrenEmpty,
	)
	return i, err
}

const listSiteStatusesByOrg = `-- name: ListSiteStatusesByOrg :many
SELECT site_id, organization_id, status, children_ready, children_processing, children_attention, children_empty FROM v_site_status
WHERE organization_id = $1
`

func (q *Queries) ListSiteStatusesByOrg(ctx context.Context, organizationID uuid.UUID) ([]VSiteStatus, error) {
	rows, err := q.db.Query(ctx, listSiteStatusesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VSiteStatus{}
	for rows.Next() {
		var i VSiteStatus
		if err := rows.Scan(
			&i.SiteID,
			&i.OrganizationID,
			&i.Status,
			&i.ChildrenReady,
			&i.ChildrenProcessing,
			&i.ChildrenAttention,
			&i.ChildrenEmpty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
