// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_audit_log.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSiteAuditEvent = `-- name: CreateSiteAuditEvent :one
INSERT INTO site_audit_log (organization_id, site_id, actor_user_id, event_type, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, site_id, actor_user_id, event_type, payload, created_at
`

type CreateSiteAuditEventParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	SiteID         uuid.UUID       `json:"site_id"`
	ActorUserID    pgtype.UUID     `json:"actor_user_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
}

func (q *Queries) CreateSiteAuditEvent(ctx context.Context, arg CreateSiteAuditEventParams) (SiteAuditLog, error) {
	row := q.db.QueryRow(ctx, createSiteAuditEvent,
		arg.OrganizationID,
		arg.SiteID,
		arg.ActorUserID,
		arg.EventType,
		arg.Payload,
	)
	var i SiteAuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SiteID,
		&i.ActorUserID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listSiteAuditLogBySite = `-- name: ListSiteAuditLogBySite :many
SELECT id, organization_id, site_id, actor_user_id, event_type, payload, created_at FROM site_audit_log
WHERE site_id = $1 AND organization_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListSiteAuditLogBySiteParams struct {
	SiteID         uuid.UUID `json:"site_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListSiteAuditLogBySite(ctx context.Context, arg ListSiteAuditLogBySiteParams) ([]SiteAuditLog, error) {
	rows, err := q.db.Query(ctx, listSiteAuditLogBySite,
		arg.SiteID,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteAuditLog{}
	for rows.Next() {
		var i SiteAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SiteID,
			&i.ActorUserID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
