// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_invitation.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptUserInvitation = `-- name: AcceptUserInvitation :one
UPDATE user_invitations
SET accepted_at = now()
WHERE id = $1 AND accepted_at IS NULL
RETURNING id, organization_id, email, role, invited_by, token_hash, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptUserInvitation(ctx context.Context, id uuid.UUID) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, acceptUserInvitation, id)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserInvitation = `-- name: CreateUserInvitation :one
INSERT INTO user_invitations (organization_id, email, role, invited_by, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, email, role, invited_by, token_hash, expires_at, accepted_at, created_at
`

type CreateUserInvitationParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Email          string      `json:"email"`
	Role           string      `json:"role"`
	InvitedBy      pgtype.UUID `json:"invited_by"`
	TokenHash      string      `json:"token_hash"`
	ExpiresAt      time.Time   `json:"expires_at"`
}

func (q *Queries) CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, createUserInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserInvitation = `-- name: DeleteUserInvitation :execrows
DELETE FROM user_invitations
WHERE id = $1 AND organization_id = $2
`

type DeleteUserInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteUserInvitation(ctx context.Context, arg DeleteUserInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserInvitation, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserInvitationByTokenHash = `-- name: GetUserInvitationByTokenHash :one
SELECT id, organization_id, email, role, invited_by, token_hash, expires_at, accepted_at, created_at FROM user_invitations WHERE token_hash = $1
`

func (q *Queries) GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getUserInvitationByTokenHash, tokenHash)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserInvitationsByOrg = `-- name: ListUserInvitationsByOrg :many
SELECT id, organization_id, email, role, invited_by, token_hash, expires_at, accepted_at, created_at FROM user_invitations
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserInvitationsByOrg(ctx context.Context, organizationID uuid.UUID) ([]UserInvitation, error) {
	rows, err := q.db.Query(ctx, listUserInvitationsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInvitation{}
	for rows.Next() {
		var i UserInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
