DROP TABLE IF EXISTS document_tasks;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS construction_sites;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organizations;

DROP EXTENSION IF EXISTS vector;
