// MockStore was generated by mockery (make mock) and then hand-edited.
// ExecTx is intentionally hand-written: it propagates the error returned by fn
// so that inner method expectations (CreateOrganization, CreateUser, etc.) fire
// naturally and their errors reach the service layer.
// When regenerating with make mock, restore ExecTx manually after generation.

package mock

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	repository "go-kpi-tenders/internal/repository"

	uuid "github.com/google/uuid"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

// CreateConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateConstructionSite(ctx context.Context, arg repository.CreateConstructionSiteParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateConstructionSite")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateConstructionSiteParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateConstructionSiteParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDocument provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateDocument(ctx context.Context, arg repository.CreateDocumentParams) (repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocument")
	}

	var r0 repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentParams) (repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentParams) repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDocumentTask provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateDocumentTask(ctx context.Context, arg repository.CreateDocumentTaskParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocumentTask")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateDocumentTaskParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrganization provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateOrganization(ctx context.Context, arg repository.CreateOrganizationParams) (repository.Organization, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateOrganizationParams) (repository.Organization, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateOrganizationParams) repository.Organization); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateOrganizationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateUser(ctx context.Context, arg repository.CreateUserParams) (repository.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserParams) (repository.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserParams) repository.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockStore) DeleteConstructionSite(ctx context.Context, arg repository.DeleteConstructionSiteParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConstructionSite")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteConstructionSiteParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteConstructionSiteParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDocument provides a mock function with given fields: ctx, arg
func (_m *MockStore) DeleteDocument(ctx context.Context, arg repository.DeleteDocumentParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDocumentTask provides a mock function with given fields: ctx, arg
func (_m *MockStore) DeleteDocumentTask(ctx context.Context, arg repository.DeleteDocumentTaskParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentTask")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentTaskParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentTaskParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteDocumentTaskParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOrganization provides a mock function with given fields: ctx, id
func (_m *MockStore) DeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecTx delegates to a pre-configured error OR executes fn(m) so that
// inner method expectations on MockStore are triggered correctly.
func (_m *MockStore) ExecTx(ctx context.Context, fn func(repository.Querier) error) error {
	args := _m.Called(ctx, fn)
	if args.Error(0) != nil {
		return args.Error(0)
	}
	return fn(_m)
}

// GetConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockStore) GetConstructionSite(ctx context.Context, arg repository.GetConstructionSiteParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetConstructionSite")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetConstructionSiteParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetConstructionSiteParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDocument provides a mock function with given fields: ctx, arg
func (_m *MockStore) GetDocument(ctx context.Context, arg repository.GetDocumentParams) (repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentParams) (repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentParams) repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDocumentTask provides a mock function with given fields: ctx, arg
func (_m *MockStore) GetDocumentTask(ctx context.Context, arg repository.GetDocumentTaskParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentTask")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentTaskParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentTaskParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetDocumentTaskParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationByID provides a mock function with given fields: ctx, id
func (_m *MockStore) GetOrganizationByID(ctx context.Context, id uuid.UUID) (repository.Organization, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.Organization, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.Organization); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationByINN provides a mock function with given fields: ctx, inn
func (_m *MockStore) GetOrganizationByINN(ctx context.Context, inn pgtype.Text) (repository.Organization, error) {
	ret := _m.Called(ctx, inn)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByINN")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) (repository.Organization, error)); ok {
		return rf(ctx, inn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) repository.Organization); ok {
		r0 = rf(ctx, inn)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Text) error); ok {
		r1 = rf(ctx, inn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockStore) GetUserByEmail(ctx context.Context, email string) (repository.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockStore) GetUserByID(ctx context.Context, id uuid.UUID) (repository.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConstructionSitesByOrganization provides a mock function with given fields: ctx, organizationID
func (_m *MockStore) ListConstructionSitesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]repository.ConstructionSite, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListConstructionSitesByOrganization")
	}

	var r0 []repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ConstructionSite, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ConstructionSite); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ConstructionSite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDocumentsByOrganization provides a mock function with given fields: ctx, organizationID
func (_m *MockStore) ListDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]repository.Document, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListDocumentsByOrganization")
	}

	var r0 []repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.Document, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.Document); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDocumentsBySite provides a mock function with given fields: ctx, arg
func (_m *MockStore) ListDocumentsBySite(ctx context.Context, arg repository.ListDocumentsBySiteParams) ([]repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListDocumentsBySite")
	}

	var r0 []repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListDocumentsBySiteParams) ([]repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListDocumentsBySiteParams) []repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListDocumentsBySiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasksByDocument provides a mock function with given fields: ctx, arg
func (_m *MockStore) ListTasksByDocument(ctx context.Context, arg repository.ListTasksByDocumentParams) ([]repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListTasksByDocument")
	}

	var r0 []repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksByDocumentParams) ([]repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksByDocumentParams) []repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DocumentTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListTasksByDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateConstructionSite(ctx context.Context, arg repository.UpdateConstructionSiteParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConstructionSite")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDocumentTaskStatus provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateDocumentTaskStatus(ctx context.Context, arg repository.UpdateDocumentTaskStatusParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentTaskStatus")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateDocumentTaskStatusParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateDocumentTaskStatusParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateDocumentTaskStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrganization provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateOrganization(ctx context.Context, arg repository.UpdateOrganizationParams) (repository.Organization, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateOrganizationParams) (repository.Organization, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateOrganizationParams) repository.Organization); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateOrganizationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
