// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	repository "go-kpi-tenders/internal/repository"

	uuid "github.com/google/uuid"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

// AcceptUserInvitation provides a mock function with given fields: ctx, id
func (_m *MockQuerier) AcceptUserInvitation(ctx context.Context, id uuid.UUID) (repository.UserInvitation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AcceptUserInvitation")
	}

	var r0 repository.UserInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.UserInvitation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.UserInvitation); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.UserInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddDocumentToComparisonSession provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) AddDocumentToComparisonSession(ctx context.Context, arg repository.AddDocumentToComparisonSessionParams) (repository.ComparisonSessionDocument, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AddDocumentToComparisonSession")
	}

	var r0 repository.ComparisonSessionDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AddDocumentToComparisonSessionParams) (repository.ComparisonSessionDocument, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AddDocumentToComparisonSessionParams) repository.ComparisonSessionDocument); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ComparisonSessionDocument)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AddDocumentToComparisonSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BatchUpsertExtractedData provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) BatchUpsertExtractedData(ctx context.Context, arg repository.BatchUpsertExtractedDataParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpsertExtractedData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.BatchUpsertExtractedDataParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateArtifactDocument provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateArtifactDocument(ctx context.Context, arg repository.CreateArtifactDocumentParams) (repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactDocument")
	}

	var r0 repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateArtifactDocumentParams) (repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateArtifactDocumentParams) repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateArtifactDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateComparisonSession provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateComparisonSession(ctx context.Context, arg repository.CreateComparisonSessionParams) (repository.ComparisonSession, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateComparisonSession")
	}

	var r0 repository.ComparisonSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateComparisonSessionParams) (repository.ComparisonSession, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateComparisonSessionParams) repository.ComparisonSession); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ComparisonSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateComparisonSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateConstructionSite(ctx context.Context, arg repository.CreateConstructionSiteParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateConstructionSite")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateConstructionSiteParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateConstructionSiteParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateContractKind provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateContractKind(ctx context.Context, arg repository.CreateContractKindParams) (repository.DocumentContractKind, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateContractKind")
	}

	var r0 repository.DocumentContractKind
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateContractKindParams) (repository.DocumentContractKind, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateContractKindParams) repository.DocumentContractKind); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentContractKind)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateContractKindParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDocument provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateDocument(ctx context.Context, arg repository.CreateDocumentParams) (repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocument")
	}

	var r0 repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentParams) (repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentParams) repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDocumentTask provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateDocumentTask(ctx context.Context, arg repository.CreateDocumentTaskParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocumentTask")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateDocumentTaskParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDocumentTaskForRequest provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateDocumentTaskForRequest(ctx context.Context, arg repository.CreateDocumentTaskForRequestParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocumentTaskForRequest")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskForRequestParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskForRequestParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateDocumentTaskForRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDocumentTaskSingleton provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateDocumentTaskSingleton(ctx context.Context, arg repository.CreateDocumentTaskSingletonParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocumentTaskSingleton")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskSingletonParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateDocumentTaskSingletonParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateDocumentTaskSingletonParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateExtractionRequest provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateExtractionRequest(ctx context.Context, arg repository.CreateExtractionRequestParams) (repository.ExtractionRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateExtractionRequest")
	}

	var r0 repository.ExtractionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateExtractionRequestParams) (repository.ExtractionRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateExtractionRequestParams) repository.ExtractionRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ExtractionRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateExtractionRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateFileRole provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateFileRole(ctx context.Context, arg repository.CreateFileRoleParams) (repository.DocumentFileRole, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateFileRole")
	}

	var r0 repository.DocumentFileRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateFileRoleParams) (repository.DocumentFileRole, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateFileRoleParams) repository.DocumentFileRole); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentFileRole)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateFileRoleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrganization provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateOrganization(ctx context.Context, arg repository.CreateOrganizationParams) (repository.Organization, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateOrganizationParams) (repository.Organization, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateOrganizationParams) repository.Organization); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateOrganizationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSiteAuditEvent provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateSiteAuditEvent(ctx context.Context, arg repository.CreateSiteAuditEventParams) (repository.SiteAuditLog, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSiteAuditEvent")
	}

	var r0 repository.SiteAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateSiteAuditEventParams) (repository.SiteAuditLog, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateSiteAuditEventParams) repository.SiteAuditLog); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.SiteAuditLog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateSiteAuditEventParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUser(ctx context.Context, arg repository.CreateUserParams) (repository.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserParams) (repository.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserParams) repository.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUserInvitation provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUserInvitation(ctx context.Context, arg repository.CreateUserInvitationParams) (repository.UserInvitation, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserInvitation")
	}

	var r0 repository.UserInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserInvitationParams) (repository.UserInvitation, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserInvitationParams) repository.UserInvitation); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.UserInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateUserInvitationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteComparisonSession provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteComparisonSession(ctx context.Context, arg repository.DeleteComparisonSessionParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComparisonSession")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteComparisonSessionParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteComparisonSessionParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteComparisonSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteConstructionSite(ctx context.Context, arg repository.DeleteConstructionSiteParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConstructionSite")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteConstructionSiteParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteConstructionSiteParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteContractKind provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteContractKind(ctx context.Context, arg repository.DeleteContractKindParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteContractKind")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteContractKindParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteContractKindParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteContractKindParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDocument provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteDocument(ctx context.Context, arg repository.DeleteDocumentParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDocumentTask provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteDocumentTask(ctx context.Context, arg repository.DeleteDocumentTaskParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentTask")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentTaskParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteDocumentTaskParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteDocumentTaskParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteFileRole provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteFileRole(ctx context.Context, arg repository.DeleteFileRoleParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFileRole")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteFileRoleParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteFileRoleParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteFileRoleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOrganization provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserInvitation provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) DeleteUserInvitation(ctx context.Context, arg repository.DeleteUserInvitationParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserInvitation")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteUserInvitationParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteUserInvitationParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.DeleteUserInvitationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetComparisonSession provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetComparisonSession(ctx context.Context, arg repository.GetComparisonSessionParams) (repository.ComparisonSession, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetComparisonSession")
	}

	var r0 repository.ComparisonSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetComparisonSessionParams) (repository.ComparisonSession, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetComparisonSessionParams) repository.ComparisonSession); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ComparisonSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetComparisonSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetConstructionSite(ctx context.Context, arg repository.GetConstructionSiteParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetConstructionSite")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetConstructionSiteParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetConstructionSiteParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContractKind provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetContractKind(ctx context.Context, arg repository.GetContractKindParams) (repository.DocumentContractKind, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetContractKind")
	}

	var r0 repository.DocumentContractKind
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetContractKindParams) (repository.DocumentContractKind, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetContractKindParams) repository.DocumentContractKind); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentContractKind)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetContractKindParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDocument provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetDocument(ctx context.Context, arg repository.GetDocumentParams) (repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentParams) (repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentParams) repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDocumentByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetDocumentByID(ctx context.Context, id uuid.UUID) (repository.Document, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentByID")
	}

	var r0 repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.Document, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.Document); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDocumentTask provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetDocumentTask(ctx context.Context, arg repository.GetDocumentTaskParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentTask")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentTaskParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetDocumentTaskParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetDocumentTaskParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExtractionKeysByNames provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetExtractionKeysByNames(ctx context.Context, arg repository.GetExtractionKeysByNamesParams) ([]repository.ExtractionKey, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetExtractionKeysByNames")
	}

	var r0 []repository.ExtractionKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetExtractionKeysByNamesParams) ([]repository.ExtractionKey, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetExtractionKeysByNamesParams) []repository.ExtractionKey); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ExtractionKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetExtractionKeysByNamesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExtractionRequest provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetExtractionRequest(ctx context.Context, arg repository.GetExtractionRequestParams) (repository.ExtractionRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetExtractionRequest")
	}

	var r0 repository.ExtractionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetExtractionRequestParams) (repository.ExtractionRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetExtractionRequestParams) repository.ExtractionRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ExtractionRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetExtractionRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExtractionRequestByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetExtractionRequestByID(ctx context.Context, id uuid.UUID) (repository.ExtractionRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetExtractionRequestByID")
	}

	var r0 repository.ExtractionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.ExtractionRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.ExtractionRequest); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.ExtractionRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFileRole provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetFileRole(ctx context.Context, arg repository.GetFileRoleParams) (repository.DocumentFileRole, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetFileRole")
	}

	var r0 repository.DocumentFileRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetFileRoleParams) (repository.DocumentFileRole, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetFileRoleParams) repository.DocumentFileRole); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentFileRole)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetFileRoleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetOrganizationByID(ctx context.Context, id uuid.UUID) (repository.Organization, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.Organization, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.Organization); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationByINN provides a mock function with given fields: ctx, inn
func (_m *MockQuerier) GetOrganizationByINN(ctx context.Context, inn pgtype.Text) (repository.Organization, error) {
	ret := _m.Called(ctx, inn)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByINN")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) (repository.Organization, error)); ok {
		return rf(ctx, inn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) repository.Organization); ok {
		r0 = rf(ctx, inn)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Text) error); ok {
		r1 = rf(ctx, inn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSingletonTaskByDocument provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetSingletonTaskByDocument(ctx context.Context, arg repository.GetSingletonTaskByDocumentParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetSingletonTaskByDocument")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetSingletonTaskByDocumentParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetSingletonTaskByDocumentParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetSingletonTaskByDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSiteStatus provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetSiteStatus(ctx context.Context, arg repository.GetSiteStatusParams) (repository.VSiteStatus, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetSiteStatus")
	}

	var r0 repository.VSiteStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetSiteStatusParams) (repository.VSiteStatus, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetSiteStatusParams) repository.VSiteStatus); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.VSiteStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetSiteStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskForExtractionRequest provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetTaskForExtractionRequest(ctx context.Context, arg repository.GetTaskForExtractionRequestParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskForExtractionRequest")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetTaskForExtractionRequestParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetTaskForExtractionRequestParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetTaskForExtractionRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (repository.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetUserByID(ctx context.Context, id uuid.UUID) (repository.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repository.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repository.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByIDAndOrg provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) GetUserByIDAndOrg(ctx context.Context, arg repository.GetUserByIDAndOrgParams) (repository.GetUserByIDAndOrgRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByIDAndOrg")
	}

	var r0 repository.GetUserByIDAndOrgRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetUserByIDAndOrgParams) (repository.GetUserByIDAndOrgRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetUserByIDAndOrgParams) repository.GetUserByIDAndOrgRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.GetUserByIDAndOrgRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetUserByIDAndOrgParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInvitationByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockQuerier) GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (repository.UserInvitation, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInvitationByTokenHash")
	}

	var r0 repository.UserInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repository.UserInvitation, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repository.UserInvitation); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(repository.UserInvitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListComparisonSessionDocuments provides a mock function with given fields: ctx, sessionID
func (_m *MockQuerier) ListComparisonSessionDocuments(ctx context.Context, sessionID uuid.UUID) ([]repository.ComparisonSessionDocument, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListComparisonSessionDocuments")
	}

	var r0 []repository.ComparisonSessionDocument
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ComparisonSessionDocument, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ComparisonSessionDocument); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ComparisonSessionDocument)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListComparisonSessionsByOrg provides a mock function with given fields: ctx, organizationID
func (_m *MockQuerier) ListComparisonSessionsByOrg(ctx context.Context, organizationID uuid.UUID) ([]repository.ComparisonSession, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListComparisonSessionsByOrg")
	}

	var r0 []repository.ComparisonSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ComparisonSession, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ComparisonSession); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ComparisonSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConstructionSitesByOrganization provides a mock function with given fields: ctx, organizationID
func (_m *MockQuerier) ListConstructionSitesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]repository.ConstructionSite, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListConstructionSitesByOrganization")
	}

	var r0 []repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ConstructionSite, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ConstructionSite); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ConstructionSite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConstructionSitesByParent provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListConstructionSitesByParent(ctx context.Context, arg repository.ListConstructionSitesByParentParams) ([]repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListConstructionSitesByParent")
	}

	var r0 []repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListConstructionSitesByParentParams) ([]repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListConstructionSitesByParentParams) []repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ConstructionSite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListConstructionSitesByParentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListContractKindsByOrg provides a mock function with given fields: ctx, dollar_1
func (_m *MockQuerier) ListContractKindsByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]repository.DocumentContractKind, error) {
	ret := _m.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListContractKindsByOrg")
	}

	var r0 []repository.DocumentContractKind
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.DocumentContractKind, error)); ok {
		return rf(ctx, dollar_1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.DocumentContractKind); ok {
		r0 = rf(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DocumentContractKind)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDocumentsByParent provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListDocumentsByParent(ctx context.Context, arg repository.ListDocumentsByParentParams) ([]repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListDocumentsByParent")
	}

	var r0 []repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListDocumentsByParentParams) ([]repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListDocumentsByParentParams) []repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListDocumentsByParentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListExtractedDataForKeys provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListExtractedDataForKeys(ctx context.Context, arg repository.ListExtractedDataForKeysParams) ([]repository.ListExtractedDataForKeysRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListExtractedDataForKeys")
	}

	var r0 []repository.ListExtractedDataForKeysRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListExtractedDataForKeysParams) ([]repository.ListExtractedDataForKeysRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListExtractedDataForKeysParams) []repository.ListExtractedDataForKeysRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ListExtractedDataForKeysRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListExtractedDataForKeysParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListExtractionKeysByOrg provides a mock function with given fields: ctx, dollar_1
func (_m *MockQuerier) ListExtractionKeysByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]repository.ExtractionKey, error) {
	ret := _m.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListExtractionKeysByOrg")
	}

	var r0 []repository.ExtractionKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ExtractionKey, error)); ok {
		return rf(ctx, dollar_1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ExtractionKey); ok {
		r0 = rf(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ExtractionKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListFileRolesByOrg provides a mock function with given fields: ctx, dollar_1
func (_m *MockQuerier) ListFileRolesByOrg(ctx context.Context, dollar_1 uuid.UUID) ([]repository.DocumentFileRole, error) {
	ret := _m.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListFileRolesByOrg")
	}

	var r0 []repository.DocumentFileRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.DocumentFileRole, error)); ok {
		return rf(ctx, dollar_1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.DocumentFileRole); ok {
		r0 = rf(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DocumentFileRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPendingExtractionRequestsByDocument provides a mock function with given fields: ctx, documentID
func (_m *MockQuerier) ListPendingExtractionRequestsByDocument(ctx context.Context, documentID uuid.UUID) ([]repository.ExtractionRequest, error) {
	ret := _m.Called(ctx, documentID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingExtractionRequestsByDocument")
	}

	var r0 []repository.ExtractionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ExtractionRequest, error)); ok {
		return rf(ctx, documentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ExtractionRequest); ok {
		r0 = rf(ctx, documentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ExtractionRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRootConstructionSites provides a mock function with given fields: ctx, organizationID
func (_m *MockQuerier) ListRootConstructionSites(ctx context.Context, organizationID uuid.UUID) ([]repository.ConstructionSite, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListRootConstructionSites")
	}

	var r0 []repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ConstructionSite, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ConstructionSite); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ConstructionSite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRootDocumentsByOrganization provides a mock function with given fields: ctx, organizationID
func (_m *MockQuerier) ListRootDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]repository.Document, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListRootDocumentsByOrganization")
	}

	var r0 []repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.Document, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.Document); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRootDocumentsBySite provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListRootDocumentsBySite(ctx context.Context, arg repository.ListRootDocumentsBySiteParams) ([]repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRootDocumentsBySite")
	}

	var r0 []repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListRootDocumentsBySiteParams) ([]repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListRootDocumentsBySiteParams) []repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListRootDocumentsBySiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSiteAuditLogBySite provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListSiteAuditLogBySite(ctx context.Context, arg repository.ListSiteAuditLogBySiteParams) ([]repository.SiteAuditLog, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListSiteAuditLogBySite")
	}

	var r0 []repository.SiteAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListSiteAuditLogBySiteParams) ([]repository.SiteAuditLog, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListSiteAuditLogBySiteParams) []repository.SiteAuditLog); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SiteAuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListSiteAuditLogBySiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSiteStatusesByOrg provides a mock function with given fields: ctx, organizationID
func (_m *MockQuerier) ListSiteStatusesByOrg(ctx context.Context, organizationID uuid.UUID) ([]repository.VSiteStatus, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListSiteStatusesByOrg")
	}

	var r0 []repository.VSiteStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.VSiteStatus, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.VSiteStatus); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.VSiteStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStaleTasks provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListStaleTasks(ctx context.Context, arg repository.ListStaleTasksParams) ([]repository.ListStaleTasksRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListStaleTasks")
	}

	var r0 []repository.ListStaleTasksRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListStaleTasksParams) ([]repository.ListStaleTasksRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListStaleTasksParams) []repository.ListStaleTasksRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ListStaleTasksRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListStaleTasksParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasksByDocument provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListTasksByDocument(ctx context.Context, arg repository.ListTasksByDocumentParams) ([]repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListTasksByDocument")
	}

	var r0 []repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksByDocumentParams) ([]repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksByDocumentParams) []repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DocumentTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListTasksByDocumentParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasksByDocuments provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListTasksByDocuments(ctx context.Context, arg repository.ListTasksByDocumentsParams) ([]repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListTasksByDocuments")
	}

	var r0 []repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksByDocumentsParams) ([]repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListTasksByDocumentsParams) []repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.DocumentTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListTasksByDocumentsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserInvitationsByOrg provides a mock function with given fields: ctx, organizationID
func (_m *MockQuerier) ListUserInvitationsByOrg(ctx context.Context, organizationID uuid.UUID) ([]repository.UserInvitation, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserInvitationsByOrg")
	}

	var r0 []repository.UserInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.UserInvitation, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.UserInvitation); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.UserInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsersByOrganization provides a mock function with given fields: ctx, organizationID
func (_m *MockQuerier) ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]repository.ListUsersByOrganizationRow, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersByOrganization")
	}

	var r0 []repository.ListUsersByOrganizationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]repository.ListUsersByOrganizationRow, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []repository.ListUsersByOrganizationRow); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ListUsersByOrganizationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkStaleTaskFailed provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) MarkStaleTaskFailed(ctx context.Context, arg repository.MarkStaleTaskFailedParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for MarkStaleTaskFailed")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.MarkStaleTaskFailedParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.MarkStaleTaskFailedParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.MarkStaleTaskFailedParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkStaleTaskPending provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) MarkStaleTaskPending(ctx context.Context, arg repository.MarkStaleTaskPendingParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for MarkStaleTaskPending")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.MarkStaleTaskPendingParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.MarkStaleTaskPendingParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.MarkStaleTaskPendingParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveDocumentFromComparisonSession provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) RemoveDocumentFromComparisonSession(ctx context.Context, arg repository.RemoveDocumentFromComparisonSessionParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDocumentFromComparisonSession")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.RemoveDocumentFromComparisonSessionParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.RemoveDocumentFromComparisonSessionParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.RemoveDocumentFromComparisonSessionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetExtractionRequestResolvedSchema provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) SetExtractionRequestResolvedSchema(ctx context.Context, arg repository.SetExtractionRequestResolvedSchemaParams) (repository.ExtractionRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetExtractionRequestResolvedSchema")
	}

	var r0 repository.ExtractionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SetExtractionRequestResolvedSchemaParams) (repository.ExtractionRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.SetExtractionRequestResolvedSchemaParams) repository.ExtractionRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ExtractionRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.SetExtractionRequestResolvedSchemaParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetExtractionRequestStatus provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) SetExtractionRequestStatus(ctx context.Context, arg repository.SetExtractionRequestStatusParams) (repository.ExtractionRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetExtractionRequestStatus")
	}

	var r0 repository.ExtractionRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SetExtractionRequestStatusParams) (repository.ExtractionRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.SetExtractionRequestStatusParams) repository.ExtractionRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ExtractionRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.SetExtractionRequestStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConstructionSite provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateConstructionSite(ctx context.Context, arg repository.UpdateConstructionSiteParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConstructionSite")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateConstructionSiteParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConstructionSiteCover provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateConstructionSiteCover(ctx context.Context, arg repository.UpdateConstructionSiteCoverParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConstructionSiteCover")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteCoverParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteCoverParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateConstructionSiteCoverParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConstructionSiteType provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateConstructionSiteType(ctx context.Context, arg repository.UpdateConstructionSiteTypeParams) (repository.ConstructionSite, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConstructionSiteType")
	}

	var r0 repository.ConstructionSite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteTypeParams) (repository.ConstructionSite, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateConstructionSiteTypeParams) repository.ConstructionSite); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ConstructionSite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateConstructionSiteTypeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateContractKind provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateContractKind(ctx context.Context, arg repository.UpdateContractKindParams) (repository.DocumentContractKind, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateContractKind")
	}

	var r0 repository.DocumentContractKind
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateContractKindParams) (repository.DocumentContractKind, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateContractKindParams) repository.DocumentContractKind); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentContractKind)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateContractKindParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDocumentMeta provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateDocumentMeta(ctx context.Context, arg repository.UpdateDocumentMetaParams) (repository.Document, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentMeta")
	}

	var r0 repository.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateDocumentMetaParams) (repository.Document, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateDocumentMetaParams) repository.Document); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateDocumentMetaParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDocumentTaskStatus provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateDocumentTaskStatus(ctx context.Context, arg repository.UpdateDocumentTaskStatusParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDocumentTaskStatus")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateDocumentTaskStatusParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateDocumentTaskStatusParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateDocumentTaskStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFileRole provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateFileRole(ctx context.Context, arg repository.UpdateFileRoleParams) (repository.DocumentFileRole, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFileRole")
	}

	var r0 repository.DocumentFileRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateFileRoleParams) (repository.DocumentFileRole, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateFileRoleParams) repository.DocumentFileRole); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentFileRole)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateFileRoleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrganization provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateOrganization(ctx context.Context, arg repository.UpdateOrganizationParams) (repository.Organization, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 repository.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateOrganizationParams) (repository.Organization, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateOrganizationParams) repository.Organization); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Organization)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateOrganizationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskResultPayload provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateTaskResultPayload(ctx context.Context, arg repository.UpdateTaskResultPayloadParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskResultPayload")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateTaskResultPayloadParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateTaskResultPayloadParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateTaskResultPayloadParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUser(ctx context.Context, arg repository.UpdateUserParams) (repository.UpdateUserRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 repository.UpdateUserRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateUserParams) (repository.UpdateUserRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateUserParams) repository.UpdateUserRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.UpdateUserRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWorkerTaskStatus provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateWorkerTaskStatus(ctx context.Context, arg repository.UpdateWorkerTaskStatusParams) (repository.DocumentTask, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkerTaskStatus")
	}

	var r0 repository.DocumentTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateWorkerTaskStatusParams) (repository.DocumentTask, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateWorkerTaskStatusParams) repository.DocumentTask); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.DocumentTask)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpdateWorkerTaskStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertExtractedDatum provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpsertExtractedDatum(ctx context.Context, arg repository.UpsertExtractedDatumParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertExtractedDatum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpsertExtractedDatumParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertExtractionKey provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpsertExtractionKey(ctx context.Context, arg repository.UpsertExtractionKeyParams) (repository.ExtractionKey, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertExtractionKey")
	}

	var r0 repository.ExtractionKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpsertExtractionKeyParams) (repository.ExtractionKey, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpsertExtractionKeyParams) repository.ExtractionKey); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.ExtractionKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UpsertExtractionKeyParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
