// MockStore was initially generated by mockery (make mock) and then hand-edited.
// ExecTx is intentionally hand-written: it propagates the error returned by fn
// so that inner method expectations (CreateOrganization, CreateUser, etc.) fire
// naturally and their errors reach the service layer.
// When regenerating with make mock, restore ExecTx manually after generation.

package mock

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stretchr/testify/mock"

	"go-kpi-tenders/internal/repository"
	"go-kpi-tenders/internal/store"
)

// MockStore is a testify mock for store.Store.
// ExecTx executes fn(m) when no pre-configured error is set, allowing
// inner CreateOrganization/CreateUser expectations to fire naturally.
type MockStore struct {
	mock.Mock
}

var _ store.Store = (*MockStore)(nil)

// ExecTx delegates to a pre-configured error OR executes fn(m) so that
// inner method expectations on MockStore are triggered correctly.
func (m *MockStore) ExecTx(ctx context.Context, fn func(q repository.Querier) error) error {
	args := m.Called(ctx, fn)
	if args.Error(0) != nil {
		return args.Error(0)
	}
	return fn(m)
}

func (m *MockStore) CreateDocument(ctx context.Context, arg repository.CreateDocumentParams) (repository.Document, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).(repository.Document), args.Error(1)
}

func (m *MockStore) CreateDocumentTask(ctx context.Context, arg repository.CreateDocumentTaskParams) (repository.DocumentTask, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).(repository.DocumentTask), args.Error(1)
}

func (m *MockStore) CreateOrganization(ctx context.Context, arg repository.CreateOrganizationParams) (repository.Organization, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).(repository.Organization), args.Error(1)
}

func (m *MockStore) CreateUser(ctx context.Context, arg repository.CreateUserParams) (repository.User, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).(repository.User), args.Error(1)
}

func (m *MockStore) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	return m.Called(ctx, id).Error(0)
}

func (m *MockStore) DeleteDocumentTask(ctx context.Context, id uuid.UUID) error {
	return m.Called(ctx, id).Error(0)
}

func (m *MockStore) DeleteOrganization(ctx context.Context, id uuid.UUID) (int64, error) {
	args := m.Called(ctx, id)
	return args.Get(0).(int64), args.Error(1)
}

func (m *MockStore) GetDocument(ctx context.Context, id uuid.UUID) (repository.Document, error) {
	args := m.Called(ctx, id)
	return args.Get(0).(repository.Document), args.Error(1)
}

func (m *MockStore) GetDocumentTask(ctx context.Context, id uuid.UUID) (repository.DocumentTask, error) {
	args := m.Called(ctx, id)
	return args.Get(0).(repository.DocumentTask), args.Error(1)
}

func (m *MockStore) GetOrganizationByID(ctx context.Context, id uuid.UUID) (repository.Organization, error) {
	args := m.Called(ctx, id)
	return args.Get(0).(repository.Organization), args.Error(1)
}

func (m *MockStore) GetOrganizationByINN(ctx context.Context, inn pgtype.Text) (repository.Organization, error) {
	args := m.Called(ctx, inn)
	return args.Get(0).(repository.Organization), args.Error(1)
}

func (m *MockStore) GetUserByEmail(ctx context.Context, email string) (repository.User, error) {
	args := m.Called(ctx, email)
	return args.Get(0).(repository.User), args.Error(1)
}

func (m *MockStore) GetUserByID(ctx context.Context, id uuid.UUID) (repository.User, error) {
	args := m.Called(ctx, id)
	return args.Get(0).(repository.User), args.Error(1)
}

func (m *MockStore) ListDocumentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]repository.Document, error) {
	args := m.Called(ctx, organizationID)
	return args.Get(0).([]repository.Document), args.Error(1)
}

func (m *MockStore) ListTasksByDocument(ctx context.Context, documentID uuid.UUID) ([]repository.DocumentTask, error) {
	args := m.Called(ctx, documentID)
	return args.Get(0).([]repository.DocumentTask), args.Error(1)
}

func (m *MockStore) UpdateDocumentStatus(ctx context.Context, arg repository.UpdateDocumentStatusParams) (repository.Document, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).(repository.Document), args.Error(1)
}

func (m *MockStore) UpdateDocumentTaskStatus(ctx context.Context, arg repository.UpdateDocumentTaskStatusParams) (repository.DocumentTask, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).(repository.DocumentTask), args.Error(1)
}

func (m *MockStore) UpdateOrganization(ctx context.Context, arg repository.UpdateOrganizationParams) (repository.Organization, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).(repository.Organization), args.Error(1)
}
