// Package mock provides test doubles for the store layer.
//
// mock_querier.go — auto-generated by "make mock" from repository.Querier.
//
//	DO NOT edit manually; re-run "make mock" after sqlc changes.
//
// mock_store.go   — hand-written; embeds MockQuerier and adds ExecTx.
//
//	Never overwritten by "make mock".
package mock

import (
	"context"

	repository "go-kpi-tenders/internal/repository"
	store "go-kpi-tenders/internal/store"
)

// Compile-time assertion: MockStore must implement store.Store.
var _ store.Store = (*MockStore)(nil)

// MockStore implements store.Store for unit tests.
type MockStore struct {
	MockQuerier
}

// NewMockStore returns a new MockStore.
func NewMockStore() *MockStore {
	return &MockStore{}
}

// ExecTx checks mock.On expectations first. If the configured return is nil
// (i.e. the transaction "starts" successfully), fn(m) is called so that inner
// repository expectations fire. If On returns a non-nil error, fn is skipped
// — simulating a failed transaction begin.
func (m *MockStore) ExecTx(ctx context.Context, fn func(repository.Querier) error) error {
	args := m.Called(ctx, fn)
	if err := args.Error(0); err != nil {
		return err
	}
	return fn(m)
}
